### ISSUE TITLE
possible error in getSymbols. Could be due to a change in yahoo url address?

### ISSUE THREAD

**Issue by filipponeri** [joshuaulrich/quantmod#117]
The execution of `getSymbols` causes the following errors? Possibly due to a change in yahoo URL? 

Thank you in advance for looking at it.
```r
> library("quantmod")
> getSymbols("^FTSE", src = "yahoo")
Error in download.file(paste(yahoo.URL, "s=", Symbols.name, "&a=", from.m,  : 
  cannot open URL 'http://ichart.finance.yahoo.com/table.csv?s=^FTSE&a=0&b=01&c=2000&d=7&e=10&f=2016&g=d&q=q&y=0&z=^FTSE&x=.csv'
In addition: Warning message:
In download.file(paste(yahoo.URL, "s=", Symbols.name, "&a=", from.m,  :
  cannot open URL 'http://ichart.finance.yahoo.com/table.csv?s=^FTSE&a=0&b=01&c=2000&d=7&e=10&f=2016&g=d&q=q&y=0&z=^FTSE&x=.csv': HTTP status was '404 Not Found'
Error in download.file(paste(yahoo.URL, "s=", Symbols.name, "&a=", from.m,  : 
  cannot open URL 'http://ichart.finance.yahoo.com/table.csv?s=^FTSE&a=0&b=01&c=2000&d=7&e=10&f=2016&g=d&q=q&y=0&z=^FTSE&x=.csv'
```

**Comment by joshuaulrich** [comment]
I deleted the majority of the code in your report, since 99% was irrelevant.  Yahoo did not change the URL. They simply stopped providing this data for download.  Compare the [^FTSE historical data page](http://finance.yahoo.com/quote/%5EFTSE/history?p=^FTSE) with that for [^GSPC](http://finance.yahoo.com/quote/%5EGSPC/history?p=^GSPC).  You can see a "Download Data" link on the ^GSPC page, but not for ^FTSE.

**Comment by filipponeri** [comment]
thank you very much for your quick reply. You are right. I removed ^FTSE from the symbol list that I am using and now the code works.

**Comment by ahsaniftikharqureshi** [comment]
Can you please help me with the following error.

trying URL 'https://ichart.finance.yahoo.com/table.csv?s=ENGRO&a=0&b=01&c=2007&d=4&e=17&f=2017&g=d&q=q&y=0&z=ENGRO&x=.csv'
Error in download.file(paste(yahoo.URL, "s=", Symbols.name, "&a=", from.m,  : 
  cannot open URL 'https://ichart.finance.yahoo.com/table.csv?s=ENGRO&a=0&b=01&c=2007&d=4&e=17&f=2017&g=d&q=q&y=0&z=ENGRO&x=.csv'
In addition: Warning message:
In download.file(paste(yahoo.URL, "s=", Symbols.name, "&a=", from.m,  :
  cannot open URL 'https://ichart.finance.yahoo.com/table.csv?s=ENGRO&a=0&b=01&c=2007&d=4&e=17&f=2017&g=d&q=q&y=0&z=ENGRO&x=.csv': HTTP status was '504 Maximum Transaction Time Exceeded'

**Comment by joshuaulrich** [comment]
@ahsaniftikharqureshi it's probably related to 157.

**Comment by webzest** [comment]
if(!("quantmod" %in% as.character(installed.packages()[,1])))
  { install.packages("quantmod") }

library("quantmod")
SPY <- suppressWarnings(getSymbols("SPY", src = "google",from = "2012-01-01"))
SPY <- as.numeric(SPY$SPY.Close)[1:987]

**Comment by braverock** [comment]
You specify src='google', so this can't have anything to do with yahoo.

Your example works fine for me:
```r 
getSymbols("SPY", src = "google",from = "2012-01-01")
#[1] "SPY"
head(SPY)
#           SPY.Open SPY.High SPY.Low SPY.Close SPY.Volume
#2012-01-03   127.75   128.38  127.44    127.49   38379801
#2012-01-04   127.18   127.81  126.72    127.63   23665645
#2012-01-05   127.01   128.23  126.43    128.10   36485767
#2012-01-06   128.22   128.22  127.29    127.82   29421959
#2012-01-09   128.04   128.18  127.41    127.99   21150934
#2012-01-10   129.37   129.65  128.95    129.13   22465952
```

You'll need to specify more details of what you think the error is, including the output of `sessionInfo()`, otherwise I'll close this as invalid.

**Comment by webzest** [comment]
Yes, that is my point.  Yahoo is not working and Google does.  Tks!

 

Regards,

 

Johnny

 

------------------------------------------------

Johnny Sandaire PhD, PMP, MCAD, ITIL

Johnny Sandaire Photography <http://www.johnnysandaire.com/> 

WebZest LLC <http://www.webzest.com/> 

Panoramic Photography <http://www.jspano.com/> 

888-490-0609
