### ISSUE TITLE
User Interaction in Charts

### ISSUE THREAD

**Issue by hherrada** [joshuaulrich/quantmod#123]
Hi Josh, first of all thank you for this amazing tool. I would like to start building my own technical analysis tool and would love to have the ability to annotate the chart on the go. Have you thought about including something like this? Here is an example of how the guys at RStudio are allowing this with shiny and the plot function: http://shiny.rstudio.com/articles/plot-interaction.html

Thank you,
Hector

**Comment by joshuaulrich** [comment]
I haven't thought carefully about it, mostly because it's a hard problem.  My recommendation would be to use the functionality in shiny.  I'm not particularly interested in re-inventing and supporting a separate implementation.
