### ISSUE TITLE
problem with chart_Series inside a function

### ISSUE THREAD

**Issue by helgasoft** [joshuaulrich/quantmod#124]
Stumbled upon a weird issue - chart_Series() not working inside a function.  
Here is the code, may need a clean environment to be 100% reproducible.
```
getSymbols("AMZN")
foo <- function(tkr) { 
  chart_Series(tkr, name='test1' );     # doesn't show
  lines(c(1,20),c(200,300))              # ERROR: "plot.new has not been called yet"
}
foo(AMZN)
chart_Series(AMZN, name='test2' )   # shows normally
lines(c(1,20),c(200,300))      # overlay ok
```

PS:  chart_Series is **great** for tech.analysis! One of the very few to allow overlay graphics on top of candlestick charts.  Please keep it alive (and well).

**Comment by joshuaulrich** [comment]
You will experience this behavior whenever `chart_Series` is called in a situation where R auto-printing is suppressed (e.g. inside a function, inside a for-loop, etc).  The solution is to wrap the `chart_Series` call in `plot`.

```r
foo <- function(tkr) { 
  chart_Series(tkr, name='test1')
  lines(c(1,20),c(200,300))
}
```
