### ISSUE TITLE
add_TA() does not see local variables in a function

### ISSUE THREAD

**Issue by helgasoft** [joshuaulrich/quantmod#130]
I understand that `chart_Series` is experimental code. This works:
```r
library(quantmod)
getSymbols("PSEC", fromDate='2016-03-01')
price <- Cl(PSEC)
chart_Series(price, TA='add_TA(SMA(price,50),on=1, col=2)')
```
But inside a function it doesn't:
```r
test <- function() {
  library(quantmod)
  getSymbols("PSEC", fromDate='2016-03-01')
  price <- Cl(PSEC)
  chart_Series(price, TA='add_TA(SMA(price,50),on=1, col=2)')
}
test()		# Error in inherits(x, "xts") : object 'price' not found
```
Is there a workaround, or should we wait for fix at a later time?

**Comment by joshuaulrich** [comment]
Both your examples both work for me using 0.4-7. Please add your `sessionInfo()` output.

**Comment by helgasoft** [comment]
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] candlesticks_0.2-5    RODBC_1.3-14          quantmod_0.4-7        TTR_0.23-1           
[5] xts_0.9-7             zoo_1.7-13            timeSeries_3022.101.2 timeDate_3012.100    

loaded via a namespace (and not attached):
[1] tools_3.3.2     grid_3.3.2      lattice_0.20-34

**Comment by joshuaulrich** [comment]
I edited your code to make it easier for me to read. I didn't realize the `rm(price)` was an important part of the report.  I am able to replicate the behavior if I run the second code block in a clean session.  Thanks for the `sessionInfo()` output and sorry for the confusion.

**Comment by joshuaulrich** [comment]
I just pushed a patch.  Please checkout the branch and test it on your actual use case.

**Comment by helgasoft** [comment]
Works fine. Hope the branch is merged in master.

**Comment by joshuaulrich** [comment]
> Works fine. Hope the branch is merged in master.

Merged. Was just waiting for testing feedback.
