### ISSUE TITLE
Date time conversion for different locales

### ISSUE THREAD

**Issue by mviana** [joshuaulrich/quantmod#140]
I had a problem using the `getSymbols` from google, since I use another locale than `en_US.utf8`, the `strptime` in `getSymbols.google` does not recognize the `"%B"` tag and therefore the dates come all `NA`.

For me, the solution was simply to do a temporary setup in the `LC_TIME` inside the function. It's not beautiful and might require tests (for parallel systems, or other application):  

```r
# Save current locale
def.locale <- Sys.getlocale("LC_TIME")
# Changes the locale for google's en_US
Sys.setlocale(category="LC_TIME",locale="en_US.utf8")

fr <- xts(as.matrix(fr[,-1]),
         as.Date(strptime(fr[,1],"%d-%B-%y"),origin='1970-01-01'),
         src='google',updated=Sys.time())
colnames(fr) <- paste(toupper(gsub('\\^','',Symbols.name)),
                     c('Open','High','Low','Close','Volume'),
                     sep='.')
# convert '-' to NAs
suppressWarnings(storage.mode(fr) <- "numeric")
fr <- convert.time.series(fr=fr,return.class=return.class)
Symbols[[i]] <-toupper(gsub('\\^','',Symbols[[i]])) 
if(auto.assign)
 assign(Symbols[[i]],fr,env)
# Set locale back
Sys.setlocale(category="LC_TIME",locale="en_US.utf8")
```
Cheers

**Comment by joshuaulrich** [comment]
Thanks for the report!  I'm not sure how I feel about changing system settings inside a function though.  I will investigate alternative solutions.
