### ISSUE TITLE
getFX: Error in charToDate(x)

### ISSUE THREAD

**Issue by ViennaGuy** [joshuaulrich/quantmod#144]
```
library(quantmod)
getFX("EUR/USD")
```

> Error in charToDate(x) : 
  character string is not in a standard unambiguous format

I'm running a code that used to work until this morning, I assume oanda has changed something on their side.

**Comment by joshuaulrich** [comment]
Just pushed a couple commits that should address this issue.  Please checkout and build the `144_getFX` branch to see if everything works for you now.  You should be able to do this with:

```r
devtools::install_github("joshuaulrich/quantmod@144_getFX")
```

But note that you will need the necessary tools to build/compile C code from source.

Thanks for the report!

**Comment by andrew521** [comment]
It doesn't seem work for me.

> devtools::install_github("joshuaulrich/quantmod@144_getFX")
Downloading GitHub repo joshuaulrich/quantmod@144_getFX
from URL https://api.github.com/repos/joshuaulrich/quantmod/zipball/144_getFX
Installing quantmod
"E:/tools/R/R-3.3.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "E:/Users/Sergiu/AppData/Local/Temp/Rtmp8KlRyP/devtools51a85b0c5441/joshuaulrich-quantmod-f17b925"  \
  --library="E:/tools/R/R-3.3.3/library" --install-tests 

* installing *source* package 'quantmod' ...
** libs
e:/tools/Rtools/mingw_64/bin/gfortran      -O2  -mtune=core2 -c ohlcq.f -o ohlcq.o
e:/tools/Rtools/mingw_64/bin/gfortran      -O2  -mtune=core2 -c ohlcz.f -o ohlcz.o
e:/tools/Rtools/mingw_64/bin/gfortran      -O2  -mtune=core2 -c period.max.f -o period.max.o
e:/tools/Rtools/mingw_64/bin/gfortran      -O2  -mtune=core2 -c period.sum.f -o period.sum.o
e:/tools/Rtools/mingw_64/bin/gcc -shared -s -static-libgcc -o quantmod.dll tmp.def ohlcq.o ohlcz.o period.max.o period.sum.o -Ld:/Compiler/gcc-4.9.3/local330/lib/x64 -Ld:/Compiler/gcc-4.9.3/local330/lib -lgfortran -lm -lquadmath -LE:/tools/R/R-33~1.3/bin/x64 -lR
installing to E:/tools/R/R-3.3.3/library/quantmod/libs/x64
** R
** demo
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'lattice'
Error : package 'zoo' could not be loaded
ERROR: lazy loading failed for package 'quantmod'
* removing 'E:/tools/R/R-3.3.3/library/quantmod'
* restoring previous 'E:/tools/R/R-3.3.3/library/quantmod'
Error: Command failed (1)

**Comment by joshuaulrich** [comment]
@andrew521, that's not related to the patch.  As the error says, the lattice package cannot be loaded.  That means zoo, and therefore xts cannot be loaded.

**Comment by andrew521** [comment]
both xts and zoo  load just fine.

> library(zoo)
> library(xts)
> xt <- xts()
> zt <- zoo()
> 

any chance you can build a package?

**Comment by joshuaulrich** [comment]
> both xts and zoo load just fine.

You show that they "load just fine" from some unspecified library.  `devtools::install_github` is using `"E:/tools/R/R-3.3.3/library"`.  If lattice, zoo, and xts are not installed there, you won't be able to install quantmod there either.

> any chance you can build a package?

No, I don't have a Windows machine available.

If you want to continue this discussion, please email me.  I don't want to hijack this issue with a conversation about how to administer an R installation.

**Comment by andrew521** [comment]
how do I email you? thanks.

**Comment by joshuaulrich** [comment]
`maintainer("quantmod")`

**Comment by joshuaulrich** [comment]
While testing, I noticed seems like only the past 180 days are available now.  IIRC, you used to be able to request up to 500 days at a time, and you could get data back many years.

That suggests I need to change the documentation even more, and I should update the function so a warning is thrown if the user tries to request data before `Sys.Date()-180`.

**Comment by andrew521** [comment]
Just to confirm that the patch works fine, on both Linux and Windows. As Joshua suggested, the build failure was due to a broken lattice package.

**Comment by gaborqbiznl** [comment]
Hi Joshua,

Will there be an update on the quantmod package related to this issue?

I tried to install the: devtools::install_github("joshuaulrich/quantmod@144_getFX") but it failed due to dependencies on: gfortran-4.8   -fPIC  -g -O2  -c ohlcq.f -o ohlcq.o

Have a nice day Joshua,
Gabor

**Comment by lukerm** [comment]
Like @gaborqbiznl, I'm also having difficulties updating fix #144 from source (as it is quite finicky to get right on Windows!). I'm currently working my way through the CRAN help guide on this, but I'm not sure if I'll be able to manage. 

I don't know how often you make updates to CRAN, but _if_ there is one coming soon (including the recent fix), it would be great to know about it :)

By the way, thanks for working so quickly to work out the fix. I think there are many of us who have come to rely on this package, and appreciate your efforts!

Cheers,
Luke

**Comment by wthielen** [comment]
I haven't tried the @144 fix as I am on R 3.3.3 and for some reason it won't install devtools :( But I checked out the code of the 2 commits, and tried the widget=1 URL from the first commit, and it looks good. I can also confirm that the API only returns the latest 180 data points (I tried Jan 1st 2016 up to today, and it started with an April 9th 2017 timestamp, downwards.)
Sorry it isn't a real test, but hope this helps.

**Comment by northcob** [comment]
It worked for me.
Bill

**Comment by hlong77** [comment]
Hi Joshua
I am getting this error when trying to run and install the patch:
> devtools::install_github("joshuaulrich/quantmod@144_getFX")
Downloading GitHub repo joshuaulrich/quantmod@144_getFX
from URL https://api.github.com/repos/joshuaulrich/quantmod/zipball/144_getFX
Installing quantmod
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/cz/fc6t44kn6yl8xhb33ndsfd4w0000gn/T/RtmpTK1qLm/devtools124c954642147/joshuaulrich-quantmod-79f0e1d'  \
  --library='/Library/Frameworks/R.framework/Versions/3.3/Resources/library' --install-tests 

* installing *source* package ‘quantmod’ ...
** libs
gfortran-4.8   -fPIC  -g -O2  -c ohlcq.f -o ohlcq.o
make: gfortran-4.8: No such file or directory
make: *** [ohlcq.o] Error 1
ERROR: compilation failed for package ‘quantmod’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/quantmod’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/quantmod’

Please can you tell me how to install that patch?
Thank you,
HL

**Comment by braverock** [comment]
The error says that you don't have gfortran installed.

On Windows, that likely means you need to install the [Rtools](https://cran.r-project.org/bin/windows/Rtools/) suite.

On a Mac, you'll need [gfortran](https://cran.r-project.org/bin/macosx/tools/)

**Comment by hlong77** [comment]
Thanks Brian! (Y)

**Comment by gaborqbiznl** [comment]
Hi Brian,

Thanks for the tip! I installed the gfortran (Mac) from your link but still I receive this error:

`devtools::install_github("joshuaulrich/quantmod@144_getFX")
Downloading GitHub repo joshuaulrich/quantmod@144_getFX
from URL https://api.github.com/repos/joshuaulrich/quantmod/zipball/144_getFX
Installing quantmod
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL  \
  '/private/var/folders/sg/9rth37wj2gz_qf70dvzc2d3r0000gn/T/Rtmpre6ree/devtools1d74336ef13/joshuaulrich-quantmod-79f0e1d'  \
  --library='/Library/Frameworks/R.framework/Versions/3.3/Resources/library' --install-tests 

* installing *source* package ‘quantmod’ ...
** libs
gfortran-4.8   -fPIC  -g -O2  -c ohlcq.f -o ohlcq.o
make: gfortran-4.8: No such file or directory
make: *** [ohlcq.o] Error 1
ERROR: compilation failed for package ‘quantmod’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/quantmod’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/quantmod’
Error: Command failed (1)
> `

What could be still the issue? I have updated R and RStudio.

And thank you both Joshua and Brian for helping out with this change on Oanda's end.

**Comment by braverock** [comment]
See instructions [here](http://r.research.att.com/tools/) for things like setting the path, which is probably what you missed.

**Comment by gaborqbiznl** [comment]
Thanks Brian!

I had to use this because the gfortran 4-8 didn't appear in the right folder on MacOS Sierra (10.12.3): http://stackoverflow.com/questions/23916219/os-x-package-installation-depends-on-gfortran-4-8

This code helped: 
```
curl -O http://r.research.att.com/libs/gfortran-4.8.2-darwin13.tar.bz2
sudo tar fvxz gfortran-4.8.2-darwin13.tar.bz2 -C /

```

Thank you again for the quick help, it works now.

**Comment by jeremyaperson** [comment]
thanks for the fix.
