### ISSUE TITLE
getSymbols() error in R (while working in RStudio)

### ISSUE THREAD

**Issue by gaborqbiznl** [joshuaulrich/quantmod#151]
### Description

I tried to run the getSymbols() command in a cron job (Ubuntu 16.04) which worked perfectly up until the last few days. I tried both on Mac and Linux. I saw the update on quantmod package on cran yesterday (19th of April), and updated the package.

R code sample:
getSymbols("AAPL")

Message:
Warning in download.file(paste(yahoo.URL, "s=", Symbols.name, "&a=", from.m,  :
  "internal" method cannot handle https redirection to: 'https://ichart.finance.yahoo.com/table.csv?s=AAPL&a=0&b=01&c=2007&d=3&e=20&f=2017&g=d&q=q&y=0&z=AAPL&x=.csv'

If I try this from RStudio, it works fine. Could someone help me what is going on?

Have a great day and thanks for making such a great package as quantmod.
Gabor

**Comment by gaborqbiznl** [comment]
Previously I loaded xts library but didn't load separately the zoo library. That solved the issue.

**Comment by joshuaulrich** [comment]
This is a duplicate of #149.
