### ISSUE TITLE
Google Finance limits number of days returned per request

### ISSUE THREAD

**Issue by joshuaulrich** [joshuaulrich/quantmod#156]
It appears that Google Finance is limiting the number of observations you can download at a time to ~4000.  This affects `getSymbols.google`.

```r
R> getSymbols("XLF", from="1999-01-01", src="google")
[1] "XLF"
Warning message:
In getSymbols.google(Symbols = "XLF", env = <environment>, verbose = FALSE,  :
  google duplicate bug - missing Dec 28,29,30 of 2003
R> head(XLF)
           XLF.Open XLF.High XLF.Low XLF.Close XLF.Volume
2001-06-18    27.65    27.75   27.29     27.65     315400
2001-06-19    28.08    28.11   27.83     27.90    1447900
2001-06-20    27.90    28.38   27.90     28.05     554700
2001-06-21    28.25    29.18   28.25     29.18     604100
2001-06-22    29.10    29.10   28.74     28.80     421000
2001-06-25    28.85    28.96   28.43     28.57     200300
```

This also happens if you go to their [historical prices page for XLF](https://www.google.com/finance/historical?cid=700196&startdate=May%2014%2C%201999&enddate=May%2013%2C%202017&num=30&ei=4hgXWcCLEaqGjAGI9764Aw&start=4500), select a date range larger than 4000 days, and click the [Download to spreadsheet link](http://www.google.com/finance/historical?cid=700196&startdate=May%2014%2C%201999&enddate=May%2013%2C%202017&num=30&ei=4hgXWcCLEaqGjAGI9764Aw&start=4500&output=csv).

Need to work-around this automatically by counting the number of days between `from` and `to` and splitting the request into multiple calls if the difference is > 4000.  That includes weekends, so it should be a conservative estimate.

Also consider checking that the first observation of the final result is close to the `from` value.  Though that could be a false-positive, since the user could enter a value for `from` that has no chance of actually containing data (e.g. `"1900-01-01"`).

**Comment by arthur1616** [comment]
Here's an idea, pull multiple times and join them together. It should be possible to automate if we add some conditions.

**Comment by joshuaulrich** [comment]
Closing, since Google Finance appears to no longer provide data for download.  See #221.
