### ISSUE TITLE
Couldn't download data via getSymbols - Following is the error

### ISSUE THREAD

**Issue by ahsaniftikharqureshi** [joshuaulrich/quantmod#159]
#Error in download.file(paste(yahoo.URL, "s=", Symbols.name, "&a=", from.m,  : 
  cannot open URL 'https://ichart.finance.yahoo.com/table.csv?s=SCBPL&a=0&b=01&c=2007&d=4&e=18&f=2017&g=d&q=q&y=0&z=SCBPL&x=.csv'
In addition: Warning message:
In download.file(paste(yahoo.URL, "s=", Symbols.name, "&a=", from.m,  :
  cannot open URL 'https://ichart.finance.yahoo.com/table.csv?s=SCBPL&a=0&b=01&c=2007&d=4&e=18&f=2017&g=d&q=q&y=0&z=SCBPL&x=.csv': HTTP status was '504 Maximum Transaction Time Exceeded'

**Comment by joshuaulrich** [comment]
Closing as duplicate of #157.
