### ISSUE TITLE
Yahoo not working with getSymbols('F')

### ISSUE THREAD

**Issue by salking** [joshuaulrich/quantmod#164]
### Description
My script stopped working so I went back to basics:  

> getSymbols('F') 
Error in download.file(paste(yahoo.URL, "s=", Symbols.name, "&a=", from.m,  : 
  cannot download all files
In addition: Warning message:
In download.file(paste(yahoo.URL, "s=", Symbols.name, "&a=", from.m,  :
  URL 'https://ichart.finance.yahoo.com/table.csv?s=F&a=0&b=01&c=2007&d=4&e=26&f=2017&g=d&q=q&y=0&z=F&x=.csv': status was '404 Not Found'

### Expected behavior
Changing the source to google works.
> getSymbols('F', src='google')
[1] "F"

### Minimal, reproducible example

[Insert sample data and code]
> getSymbols('F') 

### Session Info

Package: quantmod
 Version: 0.4-8
 Maintainer: Joshua M. Ulrich <josh.m.ulrich@gmail.com>
 Built: R 3.3.2; ; 2017-04-19 12:06:23 UTC; unix

R Version:
 platform = x86_64-apple-darwin13.4.0
 arch = x86_64
 os = darwin13.4.0
 system = x86_64, darwin13.4.0
 status = 
 major = 3
 minor = 3.3
 year = 2017
 month = 03
 day = 06
 svn rev = 72310
 language = R
 version.string = R version 3.3.3 (2017-03-06)
 nickname = Another Canoe

GUI:
 R-GUI 1.69 (7328)

Locale:
 en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

Search Path:
 .GlobalEnv, package:Rssa, package:forecast, package:svd, package:quantmod, package:TTR, package:xts, package:zoo, tools:RGUI, package:stats,
 package:graphics, package:grDevices, package:utils, package:datasets, package:methods, Autoloads, package:base
[Insert your sessionInfo() output]

**Comment by joshuaulrich** [comment]
This was fixed in #157. Please update to the latest development version before reporting bugs, so you don't spend your time reporting something that has already been reported and fixed.
