### ISSUE TITLE
error with getSymbol

### ISSUE THREAD

**Issue by makubex85** [joshuaulrich/quantmod#167]
### Description
Hi!
I am working with RStudio and R version 3.3.3.
I downloaded the r-devel version quantmod_0.4-9

### Expected behavior

When calling the function:
getSymbols('MSFT',src='yahoo')

I get the error:
Error in curl::curl_download("https://finance.yahoo.com", tmp, handle = h) : 
  Couldn't connect to server

**Comment by joshuaulrich** [comment]
That means there's something preventing your computer from connection to Yahoo Finance.  It's not a problem with quantmod.  Can you access Yahoo Finance from your browser?  Are you behind a proxy?

**Comment by makubex85** [comment]
Thank you! Well yes I can access yahoo finance from my browser and downloading with src="google" works fine... Maybe there is something preventing the access. I actually try to do it from a company so there might be some restrictions...

**Comment by joshuaulrich** [comment]
> downloading with src="google" works fine

Hmm, Google uses http:// still, while Yahoo uses https://.  FRED uses https://, so you could see if `getSymbols("GDP", src = "FRED")` works.  If not, you might need to configure [RStudio to use a proxy](https://support.rstudio.com/hc/en-us/articles/200488488-Configuring-R-to-Use-an-HTTP-Proxy)?

**Comment by makubex85** [comment]
Thank you. Well getSymbols("GDP", src = "FRED") works fine too :-/

**Comment by makubex85** [comment]
Problem solved! It was acutally the proxy. Changed the connexion and it worked! Thank you for your time!
