### ISSUE TITLE
Error using GetSymbols with Yahoo as source

### ISSUE THREAD

**Issue by arpan74** [joshuaulrich/quantmod#178]
### Description

Getting an error with GetSymbols when using Yahoo as the source. I've tried different tickers for well known stocks (AAPL, GOOGL, etc.) and have been getting an error for all of them.

The error is
`Error in curl::curl_download(cu, tmp, handle = h) : 
  Couldn't connect to server
`

### Expected behavior

Trying to get a CSV of OHLC data for a certain exchange traded name (ETF).

### Minimal, reproducible example

```r
getSymbols("OIH", src = "yahoo", auto.assign=FALSE)[,1:5]
```

### Session Info

```r
R version 3.4.1 RC (2017-06-22 r72857)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server >= 2012 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] quantmod_0.4-10 TTR_0.23-1      xts_0.9-7       zoo_1.8-0      

loaded via a namespace (and not attached):
[1] compiler_3.4.1  tools_3.4.1     curl_2.7        grid_3.4.1     
[5] lattice_0.20-35
```

**Comment by joshuaulrich** [comment]
The "Couldn't connect to server" error is caused by something preventing your R session from reaching the internet.  Are you behind a proxy?  What's the output from running the command below?

```r
w <- curl::curl_fetch_memory("https://finance.yahoo.com",curl::new_handle(verbose=TRUE))
```

**Comment by arpan74** [comment]
@joshuaulrich 

Thanks for the help! I ran that and the output is 
`> w <- curl::curl_fetch_memory("https://finance.yahoo.com",curl::new_handle(verbose=TRUE))
* Rebuilt URL to: https://finance.yahoo.com/
* timeout on name lookup is not supported
* Hostname in DNS cache was stale, zapped
*   Trying 98.139.199.204...
* TCP_NODELAY set
* After 5000ms connect time, move on!
* connect to 98.139.199.204 port 443 failed: Timed out
*   Trying 98.139.199.205...
* TCP_NODELAY set
* After 2398ms connect time, move on!
* connect to 98.139.199.205 port 443 failed: Timed out
* Failed to connect to finance.yahoo.com port 443: Timed out
* Closing connection 3
Error in curl::curl_fetch_memory("https://finance.yahoo.com", curl::new_handle(verbose = TRUE)) : 
  Couldn't connect to server`
