### ISSUE TITLE
How to add KDJ Index with quantmod?

### ISSUE THREAD

**Issue by Shicheng-Guo** [joshuaulrich/quantmod#183]
### Description

[Describe the issue]

### Expected behavior

[Describe the behavior/output you expected]

### Minimal, reproducible example

```r
[Insert sample data and code]
```

### Session Info

```r
[Insert your sessionInfo() output]
```

**Comment by braverock** [comment]
closing

1. the report is incomplete, and didn't provide any of the requested details
1. this is not a help forum

If you believe that you have found a problem in quantmod, and wish to provide the details required for someone to help resolve the problem, please edit your initial comment to provide the required details, and someone will take a look.

**Comment by Shicheng-Guo** [comment]
I mean I found the important indicator "KDJ indicator" is missed in quantmod. 

KDJ

KDJ indicator is a technical indicator used to analyze and predict changes in stock trends and price patterns in a traded asset. KDJ indicator is also known as the random index. It is a very practical technical indicator which is most commonly used in market trend analysis of short-term stock.

KDJ is a derived form of the Stochastic Oscillator Indicator with the only difference of having an extra line called the J line. Values of %K and %D lines show if the security is overbought (over 80) or oversold (below 20). The moments of %K crossing %D are the moments for selling or buying. The J line represents the divergence of the %D value from the %K. The value of J can go beyond [0, 100] for %K and %D lines on the chart.

Mathematical description: KDJ Mathematical Description.

**Comment by joshuaulrich** [comment]
The quantmod package doesn't contain *any* technical indicators.  They are all in [TTR](https://github.com/joshuaulrich/TTR).

Regardless, the description you provide says that the only difference between the "KDJ" indicator and the stochastic oscillator is the addition of "the J line", which is described as the difference between %D and %K.  This is something you can easily calculate using the output from the `stoch()` function.  It's not clear to me that it warrants a completely new function.
