### ISSUE TITLE
i CNAT DOWNLOAD QUANTMOOD ? 

### ISSUE THREAD

**Issue by Kalghamdi12** [joshuaulrich/quantmod#193]
Loading required package: TTR
Error: package or namespace load failed for ‘TTR’ in library.dynam(lib, package, package.lib):
 DLL ‘TTR’ not found: maybe not installed for this architecture?
Error: package ‘TTR’ could not be loaded
In addition: Warning messages:
1: package ‘quantmod’ was built under R version 3.4.2 
2: package ‘xts’ was built under R version 3.4.2 
3: package ‘zoo’ was built under R version 3.4.2

**Comment by joshuaulrich** [comment]
I'm closing this because it is not a problem with quantmod.  The error message asks, "maybe not installed for this architecture?"  Is that the case?  I don't know what architecture you're running, because you didn't include `sessionInfo()` output like the issue template asked...
