### ISSUE TITLE
getSymbols.av should use https

### ISSUE THREAD

**Issue by dmurdoch** [joshuaulrich/quantmod#196]
### Description

The `getSymbol.av` function creates a URL using

    URL <- paste0("http://www.alphavantage.co/query", "?function=", 
            FUNCTION, "&symbol=", sym.name, "&interval=", interval, 
            "&outputsize=", output.size, "&datatype=", data.type, 
            "&apikey=", api.key)

This URL redirects to the same path using https.  Unfortunately, some versions of R fail to follow the redirection:  I've seen it in R 3.3.2 R.app and R on MacOS, though RStudio works on the same system.  This causes the request to fail:

    > quantmod::getSymbols("TSE:BNS", env=NULL, src="av", period="intraday")
    Error in download.file(url = URL, destfile = tmp, quiet = !verbose) : 
      cannot open URL 'http://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=TSE:BNS&interval=1min&outputsize=compact&datatype=json&apikey=blahblah

whereas using the https URL works fine.  If I edit getSymbols.av to use https, things are fine.

### Expected behavior

The query should succeed.

### Minimal, reproducible example

```r
getSymbols("TSE:BNS", env=NULL, src="av", period="intraday")
```

### Session Info

```r
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X El Capitan 10.11.6

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] qtrade_1.4384 xts_0.10-0    zoo_1.8-0    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.13    lattice_0.20-35 digest_0.6.12   bitops_1.0-6    grid_3.3.2      jsonlite_1.5   
 [7] DBI_0.7         RSQLite_2.0     quantmod_0.4-11 rlang_0.1.2     curl_3.0        TTR_0.23-2     
[13] blob_1.1.0      xml2_1.1.1      bit64_0.9-7     RCurl_1.95-4.8  bit_1.1-12      pkgconfig_2.0.1
[19] memoise_1.1.0   tibble_1.3.4 
```

**Comment by joshuaulrich** [comment]
Thanks for the report.  Please correct me if I'm missing something, but I believe this was fixed in commit b0ab96679e5a1f84a20ab584cd429523897da8d4.
