### ISSUE TITLE
add_TA legend argument cannot be set

### ISSUE THREAD

**Issue by helgasoft** [joshuaulrich/quantmod#205]
### Description

I appears the _legend_ argument of **add_TA** cannot be changed from default 'auto' to a custom string.

### Expected behavior

I hoped add_TA would work like the standard function addTA.

### Minimal, reproducible example

```r
getSymbols('T')
chartSeries(T); addTA(EMA(Cl(T)), legend="myEMA")	# does it ok
chart_Series(T); add_TA(EMA(Cl(T)), legend="myEMA") 	   # doesn't
```

**Comment by joshuaulrich** [comment]
This is addressed by the fix for #377. That fix adds a `name` argument and removes the `legend` argument. The rationale is:

> I tried to pass user-supplied 'legend' values through the plotting functions, but it didn't work seamlessly like it does when passing the 'name' argument.
