### ISSUE TITLE
Feature request: enable getSymbols.av to retrieve weekly adjusted data

### ISSUE THREAD

**Issue by weekend325** [joshuaulrich/quantmod#212]
### Description

Presently, when requesting adjusted data, passing any periodicity argument to getSymbols.av other than "daily" results in the error "Only daily data can be adjusted". (Presently, lines 1304-1305 of getSymbols.R).

However, alpha vantage has added monthly and weekly adjusted time series, namely, TIME_SERIES_WEEKLY_ADJUSTED etc.

Is there any reason that getSymbols.R cannot be modified (at approximately lines 1304-1314) to allow getSymbols.av to access TIME_SERIES_WEEKLY_ADJUSTED if adjusted weekly data is requested?

**Comment by joshuaulrich** [comment]
Thanks for letting me know they've added that functionality to their API!  I also see they've added monthly adjusted time series too, so I've included that in my patch.
