### ISSUE TITLE
Access to yahoo with NTLM proxy

### ISSUE THREAD

**Issue by viniboyit** [joshuaulrich/quantmod#215]
### Description

I cannot download yahoo data through a Ntlm Proxy. 

### Minimal, reproducible example

```r
[test <-list(proxy="....",proxyuserpwd="mydomain\\.....",proxyauth="ntlm")
 getSymbols.yahoo("QQQ", curl.options = test)
]
```

### Session Info

```r
[Error in curl::handle_setopt(h, .list = curl.options) : 
  Value for option proxyauth (111) must be a number]
```

**Comment by joshuaulrich** [comment]
I don't think this is an issue with quantmod.  The documentation for [proxyauth](https://curl.haxx.se/libcurl/c/CURLOPT_PROXYAUTH.html) says that the value should be a bitmask, "constructed by or'ing together the bits fully listed and described in the [CURLOPT_HTTPAUTH](https://curl.haxx.se/libcurl/c/CURLOPT_HTTPAUTH.html) man page."  Have you tried that?

**Comment by viniboyit** [comment]
Thanks for the answer. I saw it but I don't know which value I should put.  Which one should I insert ?

**Comment by joshuaulrich** [comment]
According to [curl.h](https://github.com/curl/curl/blob/65ceb20dfd3c1820b6af9c418a0ac2885dd6b4f2/include/curl/curl.h#L704), you want `1` shifted 3 bits left.  I'm not sure if `curl` expects that as `100` or `1 * 2^3`.  So try `proxyauth=100` and `proxyauth=8`.

**Comment by viniboyit** [comment]
Thanks Joshua. 
I tried both solution and now i get the following error:
Error in curl::curl_download(cu, tmp, handle = h) : 
  Received HTTP code 407 from proxy after CONNECT

What 's strange is I can get data through google finance with  getSymbols("NOV", src = "google")
But with finance yahoo, when I type getSymbols("QQQ"), I get the following error message:
Error in curl::curl_download(cu, tmp, handle = h) : 
  Could not resolve host: finance.yahoo.com

Do you think it is due to NTLM proxy or the Http/https protocol ?

**Comment by joshuaulrich** [comment]
Google Finance works because it doesn't require an established session like Yahoo Finance does.  IIRC, `getSymbols.google()` uses `download.file()`, while `getSymbols.yahoo()` uses `curl_download()`.

I'm out of my depth, and don't have time to research. @jeroen can you help?

**Comment by joshuaulrich** [comment]
Closing, since this doesn't appear to be a bug directly in quantmod.
