### ISSUE TITLE
Error in getQuote.yahoo

### ISSUE THREAD

**Issue by abhisr** [joshuaulrich/quantmod#219]
### Description

Undefined Column Selected - Not all quoteFormat (QF) are pulling data in getQuote()

### Reason

The query from yahoo is probably not returning the data for all required fields in getQuote.yahoo

### Error Location 
Following line is resulting in error due to undefined columns selected (fields which are not present in yahoo query json response.)

```r
[df <- data.frame(Qposix, sq[,QF])  ## line 82 of getQuote.R , part of function getQuote.yahoo ]
```

### possible fix
Add the following line after line after line 62  (and before 82)
```r
sq[,QF[!QF%in%names(sq)]]<-NA  ## Give NA value to columns not present
```

**Comment by joshuaulrich** [comment]
This looks the same as #208 to me. Is there a subtle difference I missed?

**Comment by abhisr** [comment]
its same
