### ISSUE TITLE
Fix for issue 225 missing

### ISSUE THREAD

**Issue by alanault** [joshuaulrich/quantmod#229]
Hi

I'm trying to download the fix for issue 225, which resolves the changed Oanda API for getFX, however the repo returns a 404 error (not found)?

Is the repo/fix still available? I can't find it by browsing

```r
devtools::install_github("joshuaulrich/quantmod", ref="225_getsymbols_oanda")
```

Many thanks

Alan

**Comment by joshuaulrich** [comment]
The branch no longer exists, because it has been merged to master. It has also been on CRAN for a few days.

**Comment by alanault** [comment]
Ha! Well that was a nice simple fix

Many thanks for the super quick response and the great package

Alan
