### ISSUE TITLE
[R-Forge #2165] issue when downloading prices for ticker Lowe's Companies Inc (ticker LOW)

### ISSUE THREAD

**Issue by joshuaulrich** [joshuaulrich/quantmod#24]
Submitted by: Paolo Cavatore
Assigned to: Nobody
[R-Forge link](http://r-forge.r-project.org/tracker/index.php?func=detail&aid=2165&group_id=125&atid=544)

I just wanted to point out a likely bug in the below code when downloading prices for Lowe's Companies Inc (ticker LOW)

```r
getSymbols('LOW', src='yahoo')
LOW.uA <- adjustOHLC(LOW, use.Adjusted=TRUE)

Error message:
Error in `-.default`(Lo(x), Cl(x)) : array incompatibili
```

Sounds like related to the ticker being equal to the name Low intended for the Low price.

----

Followups:

Date: 2013-07-18 01:49
Sender: jim green

```r
`Lo` <-
function(x)
{
  if(has.Lo(x))
    return(x[,grep('Low',colnames(x),ignore.case=TRUE)])
  stop('subscript out of bounds: no column name containing 'Low'')
}
```

the issue is here in the `grep`, change 'Low' to '.Low' and it will work.

----

Date: 2013-07-18 02:06
Sender: Joshua Ulrich

JimGreen: Changing the pattern from 'Low' to '\.Low' will cause this to break: `data(sample_matrix); Lo(sample_matrix)`

----

Date: 2013-07-21 00:52
Sender: jim green
maybe this?

```r
`Lo` <-
function(x)
{ 
  if(has.Lo(x)) {
      #prevent LOW.Low
      if(length(grep('\.',colnames(x)[[1]]))){
        return(x[,grep('.Low',colnames(x),ignore.case=TRUE)])
      } else {
        return(x[,grep('Low',colnames(x),ignore.case=TRUE)])
      }
  }
  stop('subscript out of bounds: no column name containing 'Low'')
}
```

----

Date: 2013-07-26 16:35
Sender: Joshua Ulrich

I think the best solution is to take advantage of the fact that the `has.*()` functions first look for an attribute that matches \* (e.g. `has.Lo()` looks for `attr(x,'Lo')`).  This would require that `Lo` use `x[,has.Lo(x,which=TRUE)]` instead of `grep()` and that `getSymbols` set those column attributes.  Thoughts?

**Comment by joshuaulrich** [comment]
Enrico Schumann made an interesting suggestion in [this thread on R-SIG-Finance](https://stat.ethz.ch/pipermail/r-sig-finance/2019q1/014758.html).

> Perhaps one could add a warning for this case, either in `Lo` or `has.Lo`?
>
>```r
>i <- grep("Low", colnames(x), ignore.case = TRUE)
>if (length(i) > 1L)
>    warning("more than one column match 'low': ",
>            paste(colnames(x)[i], collapse = " "))
>```

**Comment by dppalomar** [comment]
I just realized that this bug has not been fixed yet!!

I don't like the warning approach because it will destroy any automated system with many names.

What about a combination of two previous suggestions?:

``` r
i <- grep("Low", colnames(x), ignore.case = TRUE)
if (length(i) > 1L)
   i <- grep(".Low", colnames(x), ignore.case = TRUE)
```

**Comment by joshuaulrich** [comment]
That seems to be a promising approach.  Here's a function that uses it:

```r
lo <- function (x) 
{
    j <- has.Lo(x, which = TRUE)
    if (length(j) > 1L) {
        j <- grep(".Low", colnames(x), ignore.case = TRUE)
    }
    if (length(j) > 0L) {
        return(x[, j])
    }
    stop("subscript out of bounds: no column name containing \"Low\"")
}
```

I would want some unit tests before committing the change though.  The test that failed in Jim Green's original suggestion passes with the function above (e.g. `lo(sample_matrix)`).  I would really appreciate anyone who has thoughts about what this change may break.

**Comment by ethanbsmith** [comment]
Probably a very edge case, but maybe something like this would be a touch safer. It would handle the case where a prefix had been added to the column names like “My.LOW.Low”

```
lo <- function (x) 
{
    j <- has.Lo(x, which = TRUE)
    if (length(j) > 1L) {
        j <- grep("LOW\\.Low", colnames(x), ignore.case = TRUE)
        if(length(j) > 1L) warning("ambiguous column names: more than 1 column name containing \"Low\"")
    }
    if (length(j) > 0L) {
        return(x[, j])
    }
    stop("subscript out of bounds: no column name containing \"Low\"")
}
```

**Comment by gcpoole** [comment]
I have run into this bug too....

Have you considered using a REGEX for your pattern matching in `grep`?  You could return "T" for any instance of "low" UNLESS it is followed by a period.  For instance:

```
grepl(
  "low($|[^.]).*", 
  c("LOW.High", "LOW.Low", "Low", "low", "MSFT.Low", "slow", "Lower."),
  ignore.case = T
)

[1] FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE

```

In the pattern `low($|[^.]).*`, `low` means match the letters l, o, w, in order.
`($|[^.])` means then match the end of the string (the '$") or any character except a period (^ within [ ] means match anything other the characters following ^ within the [ ]).  The . outside of [ ] means match any character at all and the * means zero of more times.  So basically this tells the parser to "match 'low' followed by either the end of the string or as many other characters as you like, but just not a period.

I can think of one instance when this solution would fail: a ticker containing "LOW" followed by another letter.  For instance, if there were a ticker "FLOWR", the bug would re-emerge.  

The only other way I can see to solve this would be to match only columns that end in "low," which seems like a reasonable permanent solution.  To do that, use "low$" as your grep pattern:

```
grepl(
  "low($|[^.]).*", 
  c("LOW.High", "LOW.Low", "Low", "low", "MSFT.Low", "slow", "Lower."),
  ignore.case = T
)

[1] FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE

```

Perhaps implement the first solution now and warn users that in a future version, the column names will need to end with the key search words.

**Comment by IlyaKipnis** [comment]
Can't we isolate the OHLC columns by isolating the ticket name and dropping it? I.e. when we download a symbol, the colnames are something like SPY.Open, SPY.High, SPY.Low, SPY.Close, etc. Thus, we know that the descriptors occur after the last period in a symbols name. Therefore, we can throw out everything before that, thus leaving us with just the descriptors (OHLC, etc.). Does this work?

**Comment by jaryan** [comment]
I agree this seems like a nice clean way as we generate the names
internally anyway. Could still break if users rename, but that would not be
quantmod problem.

**Comment by IlyaKipnis** [comment]
That would be a case of extreme PEBKAC imo.
