### ISSUE TITLE
getQuote and obsolete Warrant

### ISSUE THREAD

**Issue by helgasoft** [joshuaulrich/quantmod#241]
### Description

Stumbled on a getQuote error which is a special case, but it might happen to others, so I think it's worth reporting.  Looks like **ACERW** is an obsolete warrant symbol, still valid in Yahoo however. As shown below, it is missing attribute _exchangeTimezoneName_ and this is the cause of the error.  Other warrants, like SLNOW or EASTW, have the attribute and work fine.
Welcoming new species from the Yahoo swamp...

### Minimal, reproducible example

```r
getQuote(c('F', 'ACERW', 'IBM'))
```
_Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 2, 3
In addition: Warning message:
In getQuote.yahoo(Symbols = c("F", "ACERW", "IBM")) :
  symbols have different timezones; converting to local time_

```r
z<-jsonlite::fromJSON('https://query1.finance.yahoo.com/v7/finance/quote?symbols=F,ACERW,IBM&fields=symbol,fullExchangeName,exchangeTimezoneName')
z$quoteResponse$result[,c('symbol','quoteType','exchangeTimezoneName')]
```
symbol | quoteType | exchangeTimezoneName
--- | --- | ---
F | EQUITY | America/New_York
ACERW | WARRANT | **&lt;NA>**
IBM | EQUITY    | America/New_York

### A more serious error
which I would consider a **bug**.
```r
getQuote(c('F','dummy1','IBM'))
```
_Error in `row.names<-.data.frame`(`*tmp*`, value = value) : 
  invalid 'row.names' length_

Obviously the second symbol is invalid.  _getQuote_ uses query1.finance.yahoo.com to get the data, and Yahoo returns data only for the other two (valid) symbols - F and IBM. Then _getQuote_ tries to match the original list of 3 symbols to the result from Yahoo and _rownames_ fails.

###  Fixing getQuote
This will fix both errors by ignoring invalid symbols and symbols with a missing timezone.
```r
...
sq <- sq[!is.na(response$quoteResponse$result$exchangeTimezoneName),]   # added line
tz <- sq[, "exchangeTimezoneName"]
...
#Qposix <- sapply(split(sq, sq$exchangeTimezoneName), convertTZ)
Qposix <- sapply(list(sq), convertTZ)   # line above replaced
...
#Symbols <- unlist(strsplit(Symbols, ","))
Symbols <- sq[, 'symbol']   # line above replaced
...
```
Maybe there is a reason to stop the execution on an invalid symbol, but to many this is disruptive and the error is nondescriptive.  Having typos, expired or delisted symbols is expected, so ignore and continue with the batch download is a viable solution.

**Comment by ethanbsmith** [comment]
I didn't see this issue before. It's very similar to  #279
the "more serious error" part will be fixed by #282, but I'm not sure about is the missing time zone since I don't have a current ticker to use to test that.

probably a good defensive move would be to modify line 60 to :
`tz <- sq[!is.na(sq[, "exchangeTimezoneName"]), "exchangeTimezoneName"]`

probably best to leave this open until we can capture some live tests data

**Comment by helgasoft** [comment]
This first issue is getting old and not reproducible.  Looks like Yahoo is not using quoteType=WARRANT anymore.  
The second issue was fixed months ago.

**Comment by joshuaulrich** [comment]
Thanks for updating this issue!
