### ISSUE TITLE
Add eodhistoricaldata.com's options data API to `getOptionChain()`

### ISSUE THREAD

**Issue by SteveBronder** [joshuaulrich/quantmod#243]
### Description

I've made a branch here that uses eodhistoricaldata.com's API to pull down options data. Given that their API returns a good bit of stuff relative to yahoo I was wondering if we could return a list of two data.frames instead of a list of a list of data.frames. I find this a good bit easier to work with personally, and since this is a new function users of the yahoo format will not be affected. 

https://github.com/SteveBronder/quantmod/tree/add_oed_options

It's reasonably cheap given that it's hard to find options data. Though they do not keep historical data (ironic given their name right?) 

https://eodhistoricaldata.com/knowledgebase/stock-options-data/

There are still some things I need to email them about to clarify wrt their data and API. I have also not had time to dive into their data to see the quality, though I plan to start collecting data this week.

### Expected behavior

Users with an api key can access the options API

### Minimal, reproducible example

```r
# API key only works for AAPL.US
AAPL.EODOPT <- getOptionChain("AAPL", Exp = "2018-11-16", src = "eodhistoricaldata",
 country = "US", api.key = "OeAFFmMliFG5orCUuwAKQ8l4WWFQ67YX")
```

**Comment by SteveBronder** [comment]
(fyi this is not a PR yet because I have to do a bunch of error catching etc.)

**Comment by joshuaulrich** [comment]
Closing because this data provider doesn't appear to offer data that isn't already available from other providers.
