### ISSUE TITLE
tiingo API token no longer results in error

### ISSUE THREAD

**Issue by joshuaulrich** [joshuaulrich/quantmod#244]
The API token provided in [this comment](https://github.com/joshuaulrich/quantmod/pull/220#issuecomment-377965954) no longer results in an error.  This causes two quantmod unit tests to fail.  They need to be corrected (or removed) to keep quantmod on CRAN.

@tiingo, can you provide a new API token that results in a usage error, or should I remove the tests?

----

NOTE: This must be resolved before  2018-08-31 to keep quantmod on CRAN.

**Comment by tiingo** [comment]
Thanks for notifying me Josh - I see why it no longer errored and have put in a permanent fix for that auth token so it will always error

Thanks for notifying me so quickly

**Comment by tiingo** [comment]
Hi Josh, just following up to make sure you are seeing the token error. Let me know if there's anything else I can do to help.

**Comment by joshuaulrich** [comment]
Sorry for not following up sooner.  I'm seeing the expected error now.  This means there are no changes needed to quantmod to keep it on CRAN, so I am closing the issue as resolved.
