### ISSUE TITLE
Is it possible to download stock-symbols or ticker of a particular country using quantmod package for R?

### ISSUE THREAD

**Issue by jsabhishek** [joshuaulrich/quantmod#245]
Let's say, I want historical price data from the Indian Stock market.
All Indian stock symbols ends with .NS or .BO
So, is there a way to download stock-symbols or tickers of a particular country using quantmod package for R ?
Thanks !

**Comment by joshuaulrich** [comment]
I don't know of any way to get all the ticker symbols for the Indian stock market.  You could look at `TTR::stockSymbols()` for ideas of how it might be done, but you would need to find a data source first.
