### ISSUE TITLE
Breaking interface change with introducing .has1sym.

### ISSUE THREAD

**Issue by SamoPP** [joshuaulrich/quantmod#261]
### Description

I have many different getSymbols.sourcename functions that used to successfully collect the data from different sources (like getSymbols.premiumdata etc.). I used to call it like getSymbols("SPY", src="premiumdata") and it worked. Up until recently (this point https://github.com/joshuaulrich/quantmod/commit/98e56df59bd98f45546639a4323cc97f5112068f#diff-7c1af948aec129974f47471b5d505e5e) where .has1sym. seem to be introduced. This creates an error in calling getSymbols:
Error in getSymbols.premiumdata(Symbols = "SPY", env = <environment>,  : 
  unused argument (.has1sym. = TRUE)

This now means I need to go and rewrite approx. 10 of custom getSymbols functions and introduce .has1sym. parameter in each of those functions and ignore it afterwards...

### Expected behavior

Interface and usage should not change/break existing code.

**Comment by braverock** [comment]
You should be handling dots (...) in all your custom functions.

Then your error wouldn't exist.

The default getSymbols function signature takes dots, so all of your getSymbols.premiumdata functions should take dots too.

**Comment by braverock** [comment]
to provide a little more context, if getSymbols was a generic, you would be *required* to support a minimum of the same function signature.

that isn't exactly the pattern here, as getSymbols calls getSymbols.src 'sub-functions', but I think it is perfectly reasonable to assume the addition of new arcguments over time, and to make sure that your sub-functions can handle this addition gracefully.

Thus the need to support dots ...

**Comment by SamoPP** [comment]
Makes sense. I added ... to all my custom getSymbols functions and it works fine now. Thanks.
