### ISSUE TITLE
  getSymbols error: Could not resolve host: finance.yahoo.com

### ISSUE THREAD

**Issue by MJL9588** [joshuaulrich/quantmod#267]
### Description
using getSymbols('MSFT') throws an error:
Error in curl::curl_download(cu, tmp, handle = h) : 
  Could not resolve host: finance.yahoo.com

working on Company PC, believe that is the cause as this works fine at home.

any workarounds?

**Comment by joshuaulrich** [comment]
My guess is that your company firewall/proxy are adding additional complexity to the request.  There are parameters you can pass via `curl.options=` to provide firewall/proxy settings, but I'm not familiar with those.  I hope you closed this because you were able to figure it out.
