### ISSUE TITLE
add support for eodhistoricaldata.com

### ISSUE THREAD

**Issue by ethanbsmith** [joshuaulrich/quantmod#274]
another data provider on the scene.: https://eodhistoricaldata.com/knowledgebase/
there API is well designed and they cover some good reference  data and batch scenarios 
pricing is quite reasonable

standard implementation would include:
`getQuote` https://eodhistoricaldata.com/knowledgebase/live-realtime-stocks-api/
`getSplits`, 'getDividends' https://eodhistoricaldata.com/knowledgebase/api-splits-dividends/
`getSymbols` https://eodhistoricaldata.com/knowledgebase/api-for-historical-data-and-volumes/ and https://eodhistoricaldata.com/knowledgebase/intraday-historical-data-api/ for intra-day

It would also be nice to extend quantmod to support some of their reference data and their bulk EOD api: https://eodhistoricaldata.com/knowledgebase/bulk-api-eod-splits-dividends/

I can run with the implementation as I'm currently testing their data and mapping symbology rules

**Comment by joshuaulrich** [comment]
Hi @ethanbsmith. This was proposed in #243.  There's an issue with their data quality that I'm not comfortable sharing publicly.  I'll email you.
