### ISSUE TITLE
GetSymbols.FRED Quantmod curreny symbols data needed

### ISSUE THREAD

**Issue by sureshvigneshbe** [joshuaulrich/quantmod#278]
Hello Team,

Needed the symbols list for FRED source in `getSymbols` function of quantmod. Can any one help on this?

```r
getSymbols(Symbols = "EURUSD",
           reload.Symbols = FALSE,
           verbose = FALSE,
           warnings = TRUE,
           src = "FRED",
           symbol.lookup = TRUE,
           auto.assign = FALSE,
           from = Sys.Date() - 1,
           to = Sys.Date()-1)
```

In the place of `Symbols = "EURUSD"`, what need to  be  used  for different currency rate to the USD. Please assist.

**Comment by joshuaulrich** [comment]
Hi @sureshvigneshbe. The issue tracker isn't the best place to ask for help. It's better to ask on StackOverflow or the R-SIG-Finance mailing list (see the [contributing guide](https://github.com/joshuaulrich/quantmod/blob/master/.github/CONTRIBUTING.md#have-a-question) for links to both).

Your question may be a good feature request, so I'm going to leave this issue open. But you should ask for help somewhere else, because few people will see your question here.

**Comment by braverock** [comment]
I have an R data.frame of all of these somewhere, but for the moment, the series themselves are all available manually here:

https://fred.stlouisfed.org/categories/94

Specifically for `EURUSD`, the FRED symbol is `DEXUSEU`.

To @joshuaulrich 's point about a feature request, it would probably be straightforward to use a lookup table to get the FRED series that corresponded to the more canonical naming for FX pairs.

**Comment by joshuaulrich** [comment]
@braverock your comment and link helped me find [this page](https://fred.stlouisfed.org/categories/94/downloaddata), where you can download all the data. The zip files contain a README that lists all the available series. We can use that for the lookup table.

**Comment by sureshvigneshbe** [comment]
Thanks Team for the support.

**Comment by sureshvigneshbe** [comment]
Hi Joshualrich,

  Sorry i need a clarity  on using of Getsymbols.oanda function as alternate currency datasource.
whether it  is a free source or Licensed paid one in R. whether the currency data Can be used for commercial purposes.?  I have raised this query in Stock overflow,  Yet to get the answer.

In R documentation it is mentioned to be supported for 180 days historical data. 

Could you clarify . Thanks in advance,

**Comment by sureshvigneshbe** [comment]
Just for your information, in my previous issue i have reported "getSymbos.Yahoo"  providing incorrect data. #277 . 
As a solution , You have suggested to use oanda as a source.

**Comment by sureshvigneshbe** [comment]
could any one please update

**Comment by joshuaulrich** [comment]
Hi Suresh. Tiingo is the only other quality FX currency source I know of that is free. Here's an example:

```r
getSymbols("EURUSD", src = "tiingo", api.key = "[your free api key]")
```

**Comment by sureshvigneshbe** [comment]
Hi Joshualrich,

      whether i could use Getsymbols.oanda as one of the source as a free source for downloading daily rates. Since Tiingo , i have verified with my api key and mentioned as it can be used for only developement purpose and not as commercial purpose. Could you clarify.

**Comment by tiingo** [comment]
@sureshvigneshbe Tiingo's APIs can be used for both commercial internal use and for display redistribution. You can find pricing for internal commercial use here: https://api.tiingo.com/pricing and if you want to display prices on an app - E-mail sales@tiingo.com. Right now FX is just launching so there early bird discounts :)

**Comment by sureshvigneshbe** [comment]
Hi Joshualrich,

  But whether i could use Getsymbols.oanda as a free source. Could you please confirm.

Thanks,
N.Suresh

**Comment by joshuaulrich** [comment]
@sureshvigneshbe I cannot confirm. I do not know Oanda's terms and conditions of use. You should investigate whether they allow what you want to do.

**Comment by sureshvigneshbe** [comment]
Hi Joshualrich,
 
   I have tried to ask whether i could use the below function in Quantmod R and download currency rates . Currently it is working without any API key. So asked the below one is free source of usage. 
Could you clarify. I am not directly using anyother oanda Api.

getSymbols(Symbols = "EUR/USD",
                                         reload.Symbols = FALSE,
                                         verbose = FALSE,
                                         warnings = TRUE,
                                         src = "oanda",
                                         symbol.lookup = TRUE,
                                         auto.assign = FALSE,
                                         from = date,
                                         to = date)

Thanks,
N.Suresh

**Comment by joshuaulrich** [comment]
I don't understand what you're asking that I haven't already answered. You originally asked about the symbol for FRED data, and @braverock answered that for you.

Then you asked:

> i need a clarity on using of Getsymbols.oanda function as alternate currency datasource.
> whether it is a free source or Licensed paid one in R. whether the currency data Can be used for commercial purposes.?

I suggested you use Tiingo, because I know they provide quality data. Then you asked:

> Since Tiingo , i have verified with my api key and mentioned as it can be used for only developement purpose and not as commercial purpose. Could you clarify.

And @tiingo answered that for you.

Then you asked:

> But whether i could use Getsymbols.oanda as a free source. Could you please confirm.

I replied:

> I do not know Oanda's terms and conditions of use. You should investigate whether they allow what you want to do.

Now you're asking again if you can use Oanda without an API key. You give an example of how you use `getSymbols.oanda` to get data, and you say that it's working. So I assume you're asking whether you can use the data for commercial purposes without an API key. I still cannot answer that question for you. You need to ask Oanda.

**Comment by joshuaulrich** [comment]
Closing, since this is a question and has been answered as best I can.
