### ISSUE TITLE
centralize getQuote strsplit processing

### ISSUE THREAD

**Issue by ethanbsmith** [joshuaulrich/quantmod#284]
### Description

`getQuote` and `getSymbols` accept ";" delimited symbols as input. Not all dispatched getQuote implementations handle this. better to consolidate this into the master `getQuote` function before dispatching to to the sources.

### Minimal, reproducible example

```r
getQuote(c("SPY;WYSIWIG"), src="tiingo")
getQuote(c("SPY;WYSIWIG"), src="av")
```

**Comment by joshuaulrich** [comment]
This is a great idea! We shouldn't repeat the same code when we can move it to the main function.
