### ISSUE TITLE
getOptionChain does not pull down last trade date and implied volatility from Yahoo

### ISSUE THREAD

**Issue by hg2581** [joshuaulrich/quantmod#304]
### Description
getOptionChain from CRAN does not pull last trade or implied volatility from Yahoo.

### Expected behavior
Both ot these should be pulled since they are useful.

### Minimal, reproducible example
getOptionChain("SPY")

**Comment by joshuaulrich** [comment]
I can add IV, but last trade is already returned in the `"Last"` column.

```r
oc <- quantmod::getOptionChain("SPY")
head(oc$puts)
                   Strike Last Chg Bid  Ask Vol   OI
SPY200518P00140000    140 0.01   0   0 0.01   1  844
SPY200518P00145000    145 0.06   0   0 0.01   3   50
SPY200518P00150000    150 0.01   0   0 0.01   2 1125
SPY200518P00155000    155 0.04   0   0 0.01   1   16
SPY200518P00160000    160 0.01   0   0 0.01  40  166
SPY200518P00165000    165 0.01   0   0 0.01   1   96
```

**Comment by hg2581** [comment]
Yes,  you are correct, I do mean lastTradeDate. Both that and IV have value.

Thank you!

**Comment by joshuaulrich** [comment]
@rjvelasquezm this should be fixed in master now.

**Comment by rjvelasquezm** [comment]
Awesome, thanks a lot!!
