### ISSUE TITLE
Yahoo Japan Error in getSymbols.yahooj XML content does not seem to be XML: '1'

### ISSUE THREAD

**Issue by tchevri** [joshuaulrich/quantmod#312]
### Description

I have a piece of code that used to run without issues for many years and here is a great opportunity to extend a warm public thank you for your awesome code (and all the help you have provided to so many folks across so many forums).

```r
require(quantmod)
getSymbols('YJ1306.T', from="1900-01-01", src = 'yahooj', auto.assign=TRUE)
```

I just ran it for the first time in a few months (it was working fine in March) and I received:

> Error in getSymbols.yahooj(Symbols = "YJ1306.T", env = <environment>,  : 
>   Unable to import “YJ1306.T”.
> XML content does not seem to be XML: '1'
> 

### Expected behavior

Usually, this call creates a variable `YJ1306.T` with the downloaded series.

### Minimal, reproducible example

```r
require(quantmod)
getSymbols('YJ1306.T', from="1900-01-01", src = 'yahooj', auto.assign=TRUE)
```

### New section, if I may: what I tried!

put `debug()` around the function call. I can see that the function calls `fdoc <- XML::htmlParse(URL)` where `URL` points to [Yahoo Japan historical data](https://info.finance.yahoo.co.jp/history/?code=1306.T&sm=1&sd=01&sy=1900&em=9&ed=01&ey=2020&tm=d&p=1)

This looks correct, so I am a little shocked this call seems to be failing...  Looks fine to me.
This said, when I tried to browse directly to the security historical data page, I landed [here](https://stocks.finance.yahoo.co.jp/stocks/history/?code=1306.T). I am not sure this is relevant, but best is to let you decide, since you would know.

MUCH appreciated any help.

### Session Info

```r
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] quantmod_0.4.17 TTR_0.24.1      xts_0.12-0      zoo_1.8-8      

loaded via a namespace (and not attached):
 [1] bookdown_0.20   lattice_0.20-41 XML_3.99-0.5    digest_0.6.25   grid_4.0.2      evaluate_0.14  
 [7] rlang_0.4.7     curl_4.3        rmarkdown_2.3.3 tools_4.0.2     xfun_0.16       yaml_2.2.1     
[13] compiler_4.0.2  htmltools_0.5.0 knitr_1.29  
```

**Comment by joshuaulrich** [comment]
Thanks for the report! This may be related to #310.  Please install the latest from this repo and see if that fixes the problem for you.  I just tried that and it worked for me.

**Comment by tchevri** [comment]
Thanks a ton! 
Same issue indeed - I am so sorry I wasted your time: epic `Google` failure which did not show #310 at all, bit infuriating...

**Comment by joshuaulrich** [comment]
No worries! It only took me a few minutes to test.  And I'm happy it's already fixed!

**Comment by joshuaulrich** [comment]
> epic `Google` failure

Not sure if you tried this, but sometimes doing an [issue search](https://github.com/joshuaulrich/quantmod/issues?q=is%3Aissue+getsymbols+yahooj+) on GitHub can help.

**Comment by tchevri** [comment]
Dear @joshuaulrich 
Looks like the issue is back!
Any ideas?!
Fyi - not the only one affected:  [see here](https://bitwalk.blogspot.com/2020/04/r-quantmod-yahoo-japan.html)

**Comment by joshuaulrich** [comment]
Hi @tchevri. I've been working on this. Could you give me a ticker that has a split and dividend(s)? That will help me test the code.

**Comment by tchevri** [comment]
I was using these lines of code dear @joshuaulrich  

```
require(quantmod)
  # getSymbols('1306.T', from="2000-01-01", src = 'yahooj')
  # getSymbols("6758.T", src="yahooj", from="2013-01-01")
  # getSymbols("9984.T", src = "yahooj")
  # tmp <- getSymbols("9984.T", src = "yahoo", auto.assign = FALSE)
YJ1306.T <- getSymbols("1306.T", from="2000-01-01", src = "yahoo", auto.assign = FALSE)
init.d <- index(YJ1306.T)[1]
etf1306 <- YJ1306.T[, 6]/as.numeric(YJ1306.T[init.d, 6])
names(etf1306) <- "Topix Total Return Index"
plot(etf1306, main = paste0("Time Series Plot of ", names(etf1306)), cex.main=2, cex.axis=1.5, cex.sub=2)

```
Thank you so much! 
As you know first hand, we can't thank you enough for all you do Joshua.
thomas

**Comment by joshuaulrich** [comment]
I just noticed that you can get this data from the regular Yahoo site. I don't know if you could do that before...

```
m <- getSymbols("9104.T", src="yahoo", from="2013-01-01", auto.assign = FALSE)
m['2021-09']
##            9104.T.Open 9104.T.High 9104.T.Low 9104.T.Close 9104.T.Volume 9104.T.Adjusted
## 2021-09-01        8540        8710       8300         8430       8842400        8135.245
## 2021-09-02        8340        8600       8300         8450       6455500        8154.545
## 2021-09-03        8530        8550       8380         8450       4967600        8154.545
## 2021-09-06        8540        9060       8520         8980       8311100        8666.014
## 2021-09-07        9100        9120       8780         8930       6665300        8617.763
## 2021-09-08        8800        8990       8790         8920       3683300        8608.112
## 2021-09-09        8900        9100       8870         8960       4108000        8646.713
## 2021-09-10        9020        9070       8930         9030       3358900        8714.266
## 2021-09-13        9000        9010       8820         8920       4125000        8608.112
## 2021-09-14        8930        9250       8880         9130       5040400        8810.770
## 2021-09-15        9070        9440       9040         9400       5282100        9071.329
## 2021-09-16        9520        9680       8950         9210      10181800        8887.972
## 2021-09-17        9220        9530       9180         9500       5845600        9167.832
## 2021-09-21        9200        9330       9080         9190       5640900        8868.671
## 2021-09-22        9200        9340       9120         9250       4117900        8926.573
## 2021-09-24        9540        9890       9500         9870       7869200        9524.896
## 2021-09-27       10020       10060       9150         9230      11461200        8907.272
## 2021-09-28        9080        9180       8380         8580      12426000        8280.000
## 2021-09-29        8130        8750       8100         8450       8919800        8450.000
## 2021-09-30        8490        8510       7520         7560       9036800        7560.000
```

**Comment by tchevri** [comment]
Just as an FYI, this is the error message I am getting, I see I did not include it earlier, apologies:

```
> getSymbols("6758.T", src="yahooj", from="2013-01-01", verbose = T)
downloading  6758.T .....

done.
Error in getSymbols.yahooj(Symbols = "6758.T", env = <environment>, verbose = TRUE,  : 
  Unable to import “6758.T”.
no applicable method for 'xml_find_all' applied to an object of class "NULL"
```

I am running `quantmod 0.4.18`, basically my `Rstudio`, `R`, and packages, etc are all fully updated on `windows 11`

**Comment by joshuaulrich** [comment]
@tchevri I just pushed a potential fix to the `312-yahooj` branch. Can you please test? It doesn't handle splits and dividends any more, because it doesn't look like the table has that data now.

**Comment by tchevri** [comment]
Sorry for the big noob question.
How do I test this?
I just tried:

`devtools::install_github("joshuaulrich/quantmod")  
Skipping install of 'quantmod' from a github remote, the SHA1 (51395f93) has not changed since last install.
  Use `force = TRUE` to force installation`

so sorry for not knowing.

**Comment by joshuaulrich** [comment]
Try `remotes::install_github("joshuaulrich/quantmod@312-yahooj")`

**Comment by tchevri** [comment]
It took a very long time to run (not sure if I am delusional, but it seems much much longer than before!), but most importantly it works without error!
Thank you so much @joshuaulrich !
Awesome.

```
getSymbols('1306.T', from="2000-01-01", src = 'yahooj')  

[1] "1306.T"
```
