### ISSUE TITLE
setDefaults for getQuote.av 

### ISSUE THREAD

**Issue by helgasoft** [joshuaulrich/quantmod#316]
### Description

Documentation says in setDefaults(name...), name = _name of function, quoted or unquoted_.  For **getQuote.av** only the quoted name works.

### Expected behavior

both quoted or unquoted names to work

### Minimal, reproducible example

```r
setDefaults(getQuote.av, api.key='xxx')
# Error in setDefaults(getQuote.av, api.key = "xxx") :   object 'getQuote.av' not found
setDefaults('quantmod:::getQuote.av', api.key='xxx')
# Error in get(fun, mode = "function", envir = envir) :   object 'quantmod:::getQuote.av' of mode 'function' was not found
setDefaults('getQuote.av', api.key='xxx')
# works, huh
```

**Comment by joshuaulrich** [comment]
Thanks for the report! It looks like this is because `getQuote.av()` is not exported from the quantmod namespace. I'll investigate.

**Comment by joshuaulrich** [comment]
This took much longer than I expected (10-12 hours), but I finally got it working. Please give it a try and let me know if you run into any edge cases.

**Comment by helgasoft** [comment]
Thank you, the updated version 0.4.17.1 works fine.
