### ISSUE TITLE
Include all fields returned by Yahoo in getOptionChain

### ISSUE THREAD

**Issue by joshuaulrich** [joshuaulrich/quantmod#318]
Only some of the fields that Yahoo Finance returns for options are returned by `getOptionChain()`. We could return all of the fields.

**Comment by clue-research** [comment]
I updated getOptionChain() to include the five Yahoo fields that were not already in the process.

Some notes:
> "contractSymbol" is useful as a primary key.
> I converted "expiration" to POSIXtc in order to facilitate analyzing theta decay.

Yeah?

**Comment by joshuaulrich** [comment]
Thanks for taking the initiative to make a PR for this!
