### ISSUE TITLE
getQuote returns NAs on a symbol containing & (ampersand) in its name

### ISSUE THREAD

**Issue by pankaj3009** [joshuaulrich/quantmod#324]
### Description

While using getQuote() on a symbol that contains an & in its name, getQuote returns a data.frame of NAs

### Minimal, reproducible example

```r
getQuote(c("M&M.NS","J&KBANK.NS"))
```

**Comment by joshuaulrich** [comment]
Thanks for the report. I can replicate and have a fix.

**Comment by pankaj3009** [comment]
Thank you. The fix works beautifully.
