### ISSUE TITLE
getFinancials

### ISSUE THREAD

**Issue by VariationLab** [joshuaulrich/quantmod#327]
How to handle getFinancials issues that Google Finance stopped providing data in March, 2018.
```
JAVA <- getFinancials('JAVA')
Error: ‘getFinancials.google’ is defunct.
Google Finance stopped providing data in March, 2018.
You could try some of the data sources via Quandl instead.
See help("Defunct") and help("quantmod-defunct")
```

**Comment by stakerauo** [comment]
According to the boys over at Stockoverflow the getFinancials function is not working as per quantmod version 0.4-15.

**Comment by joshuaulrich** [comment]
This was reported in #221. One of the comments has a link to a work-around to get Yahoo data.

In order for `getFinancials()` to work again, someone needs to implement a method for a data provider (e.g. #301).

I'm closing this since the topic is already discussed in other issues.
