### ISSUE TITLE
the error for unknown symbols is terrible

### ISSUE THREAD

**Issue by peterccarl** [joshuaulrich/quantmod#333]
### Description

When I ask for a symbol that might make sense to someone familiar with Yahoo website symbology, I get an obscure error message:

> getSymbols("^SPX")
Warning: ^SPX download failed; trying again.
Error in getSymbols.yahoo(Symbols = "^SPX", env = <environment>, verbose = FALSE,  : 
  Unable to import “^SPX”.
argument "conn" is missing, with no default

Eventually, I figure out (usually by asking Josh directly) that that's a stupid user error: the spx ticker on Yahoo is "^gspc".  D'oh!

### Expected behavior

Tell me that the symbol isn't found.

### Session Info

I'm using version 0.4.18

**Comment by joshuaulrich** [comment]
Thanks for the report! I'll step through the code to see where this breaks and throw a more informative error.
