### ISSUE TITLE
Quantmod Data Issue

### ISSUE THREAD

**Issue by 4lifersss** [joshuaulrich/quantmod#342]
### Description

I am trying to download a data using the getSymbols function and I keep retrieving an error message.
I downloaded the quantmod package then loaded the package followed by the getSymbols function and I am not able to retrieve any data from the yahoo server.

### Expected behavior

The expected behavior is for the getSymbols("AAPL") to retrieve the AAPL data. But instead, I am receiving:

Error in curl::curl_fetch_memory(cu, handle = h) :
  Timeout was reached: [finance.yahoo.com] Operation timed out after 10005 milliseconds with 0 out of 0 bytes received

**Comment by joshuaulrich** [comment]
That's almost certainly a problem with your connection to Yahoo's servers. It's probably a temporary issue.

I'm closing this because it's very unlikely there's something I can do to fix your problem. But I'm happy to try to help troubleshoot.

**Comment by 4lifersss** [comment]
I was able to fix the issue by switching computers.
