### ISSUE TITLE
`getSymbols.tiingo` should return a `Date` index

### ISSUE THREAD

**Issue by ethanbsmith** [joshuaulrich/quantmod#350]
### Description

`getSymbols.tiingo` currently only return daily sampled date, but the `index` on the data is `POSIXct`
      `tm.stamps <- as.POSIXct(stock.data[, "date"], ...)`

1. this is inconsistent with other daily data source, which use a `Date` data type on the index
2. using a `POSIXct` data type on daily data exposes the consumer to time zone issues

### Expected behavior
return the index as a `Date` data type

**Comment by joshuaulrich** [comment]
Thanks for the report! Let me know what you think of the patch in the commit I just pushed.

**Comment by ethanbsmith** [comment]
just checked the tiingo docs and they do support those other sampling frequencies. is there a reason to disallow them? would seem to be a potential breaking change. returning a `Date` index for those periodicities would match how `getSymbols.yahoo` works

![image](https://user-images.githubusercontent.com/24379655/145685727-dda64161-34cf-4d3c-b723-a695cebd438b.png)

rest looks good

**Comment by joshuaulrich** [comment]
Good find regarding that argument! I added that to the patch.

**Comment by ethanbsmith** [comment]
https://api.tiingo.com/documentation/end-of-day

**Comment by ethanbsmith** [comment]
i think just backing out the change to line 1489 in https://github.com/joshuaulrich/quantmod/commit/573f8fd84f95f424c62d75c304199d15cd60e4c8

**Comment by ethanbsmith** [comment]
scratch that. i need to do some testing

**Comment by ethanbsmith** [comment]
https://github.com/joshuaulrich/quantmod/commit/71978df0a5b5c69b67f1ff3e4ab1acadd7c77f9c looks good. thx for this!
