### ISSUE TITLE
getFX returns 404 error

### ISSUE THREAD

**Issue by andharris** [joshuaulrich/quantmod#36]
It looks like OANDA updated it's URL and page structure which has broken getFX where it is returning a 404 error.

**Comment by joshuaulrich** [comment]
Thanks for the report.

Here's an example of the new URL: http://www.oanda.com/currency/historical-rates/download?quote_currency=USD&end_date=2015-2-7&start_date=2015-1-9&period=daily&display=absolute&rate=0&data_range=d30&price=bid&view=table&base_currency_0=EUR&base_currency_1=&base_currency_2=&base_currency_3=&base_currency_4=&download=csv

I'm not familiar with the format of the data from the previous download link.  That might have also changed and would require changes to how the CSV is read.

**Comment by isomorphisms** [comment]
Thanks Josh!
