### ISSUE TITLE
Add name argument to add_TA

### ISSUE THREAD

**Issue by SamoPP** [joshuaulrich/quantmod#377]
### Description

It would be nice to have a `name` argument in add_TA function (instead of `lenv$name <- deparse(substitute(x))`).

### Expected behavior

Instead of using `lenv$name <- deparse(substitute(x))` function argument `name` (if set, not NULL) would be used.

### Minimal, reproducible example

[Insert your sessionInfo() output]

**Comment by joshuaulrich** [comment]
I just noticed that this is similar to #205. `add_TA()` and `add_Series()` have a `legend` argument to set the name. I'm going to update this fix to remove the `name` argument it added and make the fix using the `legend` argument.

**Comment by joshuaulrich** [comment]
I changed my mind. I tried to pass user-supplied 'legend' values through the plotting functions, but it didn't work seamlessly like it does when passing the 'name' argument. So I'm keeping this fix instead of doing what I said in my previous comment.
