### ISSUE TITLE
getSymbols Oanda lexical error

### ISSUE THREAD

**Issue by macray76** [joshuaulrich/quantmod#387]
When executing any getSymbols command to Oanda results in a json error rather than extracting the daily rate.

`getSymbols("EUR/GBP", src="oanda", from="2023-06-26", to="2023-06-26", auto.assign=FALSE)`

Result:
```
Error in getSymbols.oanda(Symbols = "EUR/GBP", env = <environment>, verbose = FALSE,  : 
  Unable to import “EUR/GBP”.
lexical error: invalid char in json text.
                                       <!DOCTYPE html> <html lang="en"
                     (right here) ------^
```

**Comment by jrwishart** [comment]
A URL for oanda.com is made and fed into `jsonlite::fromJSON` here https://github.com/joshuaulrich/quantmod/blob/f60b99dcac55036580c14c840c5c0763d9c97f88/R/getSymbols.R#L1152-L1163 This is now rejected by `fromJSON` with 
```
Error in parse_con(txt, bigint_as_char) : 
  lexical error: invalid char in json text.
                                       <!DOCTYPE html> <html lang="en"
                     (right here) ------^
```
I am guessing the structure of the oanda website has changed and an update to this code is required?

**Comment by QuinHsieh** [comment]
If I implement the following commend, such like `getFX("USD/JPY")` or `getMetals(c("gold","XPD"))`, it responds some the errors that can not understand.

![1688020510249](https://github.com/joshuaulrich/quantmod/assets/51399083/6dff56ec-4ef3-49cf-b8ac-84289f6fb4bf)
![1688020542581](https://github.com/joshuaulrich/quantmod/assets/51399083/b320d797-275b-451e-b942-67488c25b39b)

Could everyone solve these problems?

**Comment by JimboMahoney** [comment]
Also seeing this and suspect it's an issue with Oanda - looks like they have changed URL (as @jrwishart mentions) and/or changed their data access for some / most datasets to premium / pro 

.·´¯`(>▂<)´¯`·.
