### ISSUE TITLE
Error message with "getSymbols"

### ISSUE THREAD

**Issue by rabarros01** [joshuaulrich/quantmod#389]
### Description

Hi,

when using the function "getSymbols" in quantmod to download stock prices, I am getting the following error message for several stock tickers:

query2.finance.yahoo.com port 443: Timed out

### Expected behavior

The problem started happening about three days ago

### Minimal, reproducible example

Here is an example with two tickers

tickers = c("MSEX","AEE")
data.stocks0 = getSymbols(tickers, from = '2010-01-05', to = Sys.Date(), periodicity = "daily")
data.stocks = cbind(Cl(MSEX),Cl(AEE))

### Session Info

And the error message

Warning: Unable to import “MSEX”.
Failed to connect to query2.finance.yahoo.com port 443: Timed out
Warning: Unable to import “AEE”.
Failed to connect to query2.finance.yahoo.com port 443: Timed out

Thanks!

**Comment by joshuaulrich** [comment]
What's your `sessionInfo()` output?

**Comment by rabarros01** [comment]
Thanks for reaching out Joshua. Was just running it again, and it all went through now. I will let you know in case it happens again.

All the best,
rabarros01
