### ISSUE TITLE
yahoo getQuote failing

### ISSUE THREAD

**Issue by ethanbsmith** [joshuaulrich/quantmod#421]
### Description

on 2024-08-15, getQuote.yahoo started failing from non-gdpr countries. this issue has nothing to do with GDPR

### Minimal, reproducible example

```r
getQuote("SPY", src = "yahoo")
Error in getQuote.yahoo(Symbols = "SPY") : 
  Unable to obtain yahoo crumb. If this is being called from a GDPR country, Yahoo requires GDPR consent, which cannot be scripted
```

### Session Info

```r
[Insert your sessionInfo() output]
```

**Comment by joshuaulrich** [comment]
I can't replicate this. Maybe it was just a temporary issue with the server this morning?

**Comment by ethanbsmith** [comment]
looks that way

**Comment by joshuaulrich** [comment]
Okay, thanks for confirming. I'm going to close the PR because I'd rather not change anything unless it's necessary.
