### ISSUE TITLE
getSymbols error importing csv file

### ISSUE THREAD

**Issue by reddogg24** [joshuaulrich/quantmod#428]
### Description

[I'm trying to import a csv file but I'm getting an error:
Error in getSymbols.csv(Symbols = "C00H", env = <environment>, verbose = FALSE,  : 
  Unable to import “C00H”.
character string is not in a standard unambiguous format]

### Expected behavior

[Describe the behavior/output you expected]

### Minimal, reproducible example

```r
getSymbols('C00H',src='csv',dir='/home/bob/Downloads/data/corn')]


Here's the top of the file C00H.csv:
Date,Open,High,Low,Close,Volume,OpenInt
09-22-1998,258.5,258.75,258.5,258.75,1,1
```

### Session Info

```r
[Insert your sessionInfo() output]
```

**Comment by joshuaulrich** [comment]
You need to set `format = "%m-%d-%Y"` in the call to `getSymbols()`. I'll update the documentation to say you need to set that argument if the date is not in a standard format.

```r
getSymbols("C00H", src = "csv", dir = ".", format = "%m-%d-%Y", auto.assign = FALSE)
##            C00H.Open C00H.High C00H.Low C00H.Close C00H.Volume C00H.Adjusted
## 1998-09-22     258.5    258.75    258.5     258.75           1             1
```

**Comment by reddogg24** [comment]
It worked! Thank you.
