### ISSUE TITLE
Oanda data

### ISSUE THREAD

**Issue by michaelrempel** [joshuaulrich/quantmod#43]
None of the Oanda data feeds appear to be working.

On the other hand, Yahoo has FX data now, so that could be incorporated.

A demonstration project that accumulates EOD data, Dividends, and Financials would be of great interest to most investors, particularly if it had automated data updates. It would save reinventing that particular wheel.

Rant:
The database connection is not well documented. One should be able to set up the database connection. Similarly pointers to the return types of the data elements would be helpful to someone not familiar with the basis for the package. When documentation requires searching the source code to figure out what to do it is not really documentation. It is just a polite but inadequate source of frustration.

**Comment by joshuaulrich** [comment]
`getSymbols.oanda` works for me.

```r
> library(quantmod)
> getFX("USD/EUR")
[1] "USDEUR"
> head(USDEUR)
           USD.EUR
2013-11-11  0.7480
2013-11-12  0.7473
2013-11-13  0.7458
2013-11-14  0.7443
2013-11-15  0.7428
2013-11-16  0.7428
> getMetals("XAU")
[1] "XAUUSD"
> head(XAUUSD)
            XAU.USD
2013-11-10 1288.715
2013-11-11 1288.725
2013-11-12 1285.010
2013-11-13 1279.020
2013-11-14 1272.420
2013-11-15 1284.740
```

Pull requests to improve documentation are welcome.

**Comment by evelynmitchell** [comment]
> library(quantmod)
> getFX('USD/EUR')
Error in download.file(paste(oanda.URL, from.date, to.date, "exch=", currency.pair[1],  : 
  cannot open URL 'http://www.oanda.com/convert/fxhistory?lang=en&date1=11%2F11%2F13&date=03%2F25%2F15&date_fmt=us&exch=USD&expr2=EUR&margin_fixed=0&SUBMIT=Get+Table&format=CSV&redirected=1'
In addition: Warning message:
In download.file(paste(oanda.URL, from.date, to.date, "exch=", currency.pair[1],  :
  cannot open: HTTP status was '404 Not Found'

**Comment by joshuaulrich** [comment]
@evelynmitchell That was fixed in #36.

**Comment by michaelrempel** [comment]
Where do you upload to? Berkley USA(CA1) has 0.4-0

**Comment by joshuaulrich** [comment]
All package authors/maintainers submit to [CRAN](http://cran.r-project.org/).  I assume you're referring to the Berkley CRAN mirror by "Berkley USA(CA1)".  The Berkley CRAN mirror shows [quantmod 0.4-4](http://cran.cnr.berkeley.edu/web/packages/quantmod/), just like CRAN.  You could try the [RStudio mirror](http://cran.rstudio.com/).

**Comment by michaelrempel** [comment]
I am using 3.1.2. RRO. Package updates are not working, I think I have other problems.
