### ISSUE TITLE
getSymbols.MySQL fails to connect to database

### ISSUE THREAD

**Issue by joshuaulrich** [joshuaulrich/quantmod#45]
Summary of a Q/A on stackoverflow: [Quantmod: Error loading symbols from MySQL DB](http://stackoverflow.com/q/29333330/271616).

-----

```r
library(quantmod)
setDefaults(getSymbols.MySQL,user="****", password="****", dbname="quantmoddb")
getSymbols("myspy",src="MySQL")
#Error in (function (classes, fdef, mtable)  : 
#unable to find an inherited method for function ‘dbConnect’ for signature ‘"character"’
```
The db is set up correctly as the following code runs fine and returns the data set as expected.

```r
con <- dbConnect(RMySQL::MySQL(), user="****", password="****",
                 dbname="quantmoddb", host="localhost", port=3306) 
db.Symbols <- DBI::dbListTables(con)
query <- paste("SELECT * from myspy ORDER BY date")
rs <- DBI::dbSendQuery(con, query)
fr <- DBI::fetch(rs, n=-1)
```

This error is caused by [the removal](https://github.com/rstats-db/RMySQL/commit/051eeddcf6e8e0ccac9ae6bef42343241ff2b264#diff-30bde6a0d7563b50611c11cb8b94575cL12) of the `"character"` method for `dbConnect` in the 0.10 release of RMySQL.  Though it was not clear from the commit message nor explicitly mentioned in the release notes, [it was intentional](https://github.com/rstats-db/RMySQL/issues/62#issuecomment-87692704).

I do not have a MySQL database available for testing, so I would really appreciate some help from those who use this functionality.  Hadley suggests the fix should be simple: switch from `dbConnect("MySQL", ...)` to `dbConnect(RMySQL::MySQL(), ...)` on [line 614 of getSymbols.R](https://github.com/joshuaulrich/quantmod/blob/develop/R/getSymbols.R#L619).

**Comment by brmn** [comment]
>>switch from dbConnect("MySQL", ...) to dbConnect(RMySQL::MySQL(), ...) on line 614 of getSymbols.R.

in fact it  is line 620 at the monent

yup, it works

**Comment by joshuaulrich** [comment]
Thanks for the feedback!
