### ISSUE TITLE
Delt default calculation infelicity

### ISSUE THREAD

**Issue by joshuaulrich** [joshuaulrich/quantmod#46]
`Delt` calculates arithmetic returns by default, but the "Details" section of `?Delt` says log returns are the default.  Both the code and the "Arguments" section of `?Delt` indicate that arithmetic should be the default, so "Details" section of `?Delt` just needs to be corrected.

**Comment by evelynmitchell** [comment]
I've modified  the Delt documentation to refer to arithmetic as the default and log as  the alternate calculation. Thank you l0uis for the report.
