### ISSUE TITLE
The xts object returned from getSymbols.csv have wrong date index.

### ISSUE THREAD

**Issue by rickyu** [joshuaulrich/quantmod#48]
step:
1. I downloaded IBM history data from yahoo to file IBM.csv.
2. I called getSymbols.csv('IBM', src='csv', dir='~/data')
3. head(IBM)  ： all the date index is current date.

I read the code of getSymbols.csv and found the line 
      fr <- xts(fr[,-1], as.Date(fr[,1], format=format, origin='1970-01-01'), src='csv', updated=Sys.time())
when format is '', the fr will have wrong date index.

I suggest the default value of format should be set as '%Y-%m-%d' , rather than ''.

thanks.

rick

**Comment by joshuaulrich** [comment]
Thanks for the report. Rather than set the default format to `"%Y-%m-%d"` I will omit it from the function call entirely, unless it's supplied via `setSymbolLookup` or `...`.
