### ISSUE TITLE
getSymbols.FRED does not support https

### ISSUE THREAD

**Issue by joshuaulrich** [joshuaulrich/quantmod#56]
FRED recently changed its URLs from http:// to https://.  This causes `getSymbols.FRED` to fail on most platforms/configurations.  See [this R-SIG-Finance thread](https://stat.ethz.ch/pipermail/r-sig-finance/2015q3/013401.html), [this R-pkg-devel thread](https://stat.ethz.ch/pipermail/r-package-devel/2015q3/000193.html), and [this question on StackOverflow](http://stackoverflow.com/q/31188023/271616).

The current code still works for me on Windows if `--internet2` is set, but fails if it is not. On unix-alikes, one potential solution is to add `method="curl"` or `method="wget"` to the `download.file` call in `getSymbols.FRED`.

So far, it looks like [Winston's downloader package](https://github.com/wch/downloader) is the most promising solution.  A solution was suggested in PR #55, but it will only work on platforms with `curl` installed and on the search path.

Note to anyone considering submitting a PR: please ensure you understand the depth of
the problem. The solution must support all major platforms and be allowed by CRAN.

**Comment by jaryan** [comment]
I'm partial to exposing method= as that removes a dependency requirement and exposes underlying facility that allows for a native solution.

The code could also attempt to automagically facility via a capabilities check to make this transition transparent. 

To cover all bases a Suggests could be included for the downloader package, as a final backstop. 

Jeff

**Comment by kgtaylor** [comment]
Hello.

I work on FRED at the St. Louis Fed.  We were contacted by a user having trouble getting FRED data in his usual way.  I was able to successfully work around his problem using your method= solution.  I was also able to get something working by replacing download.file code with getURL from the RCurl package.  Unfortunately, I don't understand how libcurl works with R.  All my test machines are either unix-alikes or have libcurl installed.

Let me know if there is anything that I can do to help.  I'm happy to poke around or test things.

Sincerely,
Keith Taylor
keith.g.taylor@stls.frb.org
Federal Reserve Bank of St. Louis

**Comment by joshuaulrich** [comment]
@jaryan,

> I'm partial to exposing method= as that removes a dependency requirement and exposes underlying facility that allows for a native solution.

This would be easy.  We wouldn't need to "expose" anything.  We could simply look for `method` passed via `...` and pass that to `download.file`.  The downside is that it would not be seamless to the end user.  They would have to add the `method` argument to all their calls (or via `setSymbolLookup`).

> The code could also attempt to automagically facility via a capabilities check to make this transition transparent.

This is what `downloader::download` does, so it would make sense to just use that functionality in this case.

----
@kgtaylor,

Thanks for reaching out.  We probably won't use `RCurl::getURL`, since that would add another dependency (one that can be troublesome to build on some platforms).

When people talk about libcurl support in R, they're referring to it being built-in, which depends on how you build R (or what binary build you use).  This is a very recent addition, so users on R < 3.2.0 can't possibly have it.

**Comment by jaryan** [comment]
Thanks Josh.

I would think using downloader package is not desirable.  I would rather
have a local version of that functionality within quantmod than require an
entire package for just one function.

Note that you can also set method globally via options():

  method: Method to be used for downloading files.  Currently download
          methods ‘"internal"’, ‘"wget"’, ‘"curl"’ and ‘"lynx"’ are
          available, and there is a value ‘"auto"’: see ‘Details’.  The
          method can also be set through the option
          ‘"download.file.method"’: see ‘options()’.

Users setting to wget (or curl?) would see no issues.  While not perfectly
desirable (no change is), this is still 'pure R' and to me the lesser of
two evils.  It also requires absolutely no change to the package.

**Comment by braverock** [comment]
It seems like expecting current R > 3.2.0 isn't the end of the world.

libcurl support is pretty widely available already, and it is now in the 
core by default.

Brian


On 07/08/2015 09:03 PM, jaryan wrote:
> Thanks Josh.
>
> I would think using downloader package is not desirable. I would rather
> have a local version of that functionality within quantmod than require an
> entire package for just one function.
>
> Note that you can also set method globally via options():
>
> method: Method to be used for downloading files. Currently download
> methods ‘"internal"’, ‘"wget"’, ‘"curl"’ and ‘"lynx"’ are
> available, and there is a value ‘"auto"’: see ‘Details’. The
> method can also be set through the option
> ‘"download.file.method"’: see ‘options()’.
>
> Users setting to wget (or curl?) would see no issues. While not perfectly
> desirable (no change is), this is still 'pure R' and to me the lesser of
> two evils. It also requires absolutely no change to the package.
>
>
>
> On Wed, Jul 8, 2015 at 6:16 PM, Joshua Ulrich <notifications@github.com>
> wrote:
>
>  > @jaryan <https://github.com/jaryan>,
>  >
>  > I'm partial to exposing method= as that removes a dependency requirement
>  > and exposes underlying facility that allows for a native solution.
>  >
>  > This would be easy. We wouldn't need to "expose" anything. We could
> simply
>  > look for method passed via ... and pass that to download.file. The
>  > downside is that it would not be seamless to the end user. They would
> have
>  > to add the method argument to all their calls (or via setSymbolLookup).
>  >
>  > The code could also attempt to automagically facility via a capabilities
>  > check to make this transition transparent.
>  >
>  > This is what downloader::download does, so it would make sense to just
>  > use that functionality in this case.
>  > ------------------------------
>  >
>  > @kgtaylor <https://github.com/kgtaylor>,
>  >
>  > Thanks for reaching out. We probably won't use RCurl::getURL, since that
>  > would add another dependency (one that can be troublesome to build on
> some
>  > platforms).
>  >
>  > When people talk about libcurl support in R, they're referring to it
> being
>  > built-in, which depends on how you build R (or what binary build you
> use).
>  > This is a very recent addition, so users on R < 3.2.0 can't possibly have
>  > it.
>  >
>  > —
>  > Reply to this email directly or view it on GitHub
>  >
> <https://github.com/joshuaulrich/quantmod/issues/56#issuecomment-119756696>
>  > .
>  >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joshuaulrich/quantmod/issues/56#issuecomment-119782400>.
>


-- 
Brian G. Peterson
http://braverock.com/brian/
Ph: 773-459-4973
IM: bgpbraverock

**Comment by blackmarkt** [comment]
Thanks all for working on this bug.

@joshuaulrich "The current code still works for me on Windows if --internet2 is set, but fails if it is not."

Do you accomplish this by setinternet2() function? I am not aware of setting "--internt2". How do you accomplish this?

Thank You!

**Comment by joshuaulrich** [comment]
@blackmarkt You can use `setInternet2()` to do it.  `--internet2` is a command line option that you can set by right-clicking the shortcut that starts R, selecting "Properties" and adding it to the command used to start R.

**Comment by blackmarkt** [comment]
@joshuaulrich Thanks for all your insight!
