### ISSUE TITLE
getSymbols.yahooj: TOPIX does not download

### ISSUE THREAD

**Issue by wthielen** [joshuaulrich/quantmod#57]
TOPIX (998405.T) only has OHLC data, no volume/adjusted price, despite having a *.T code. Needs a smarter OHLC/OHLCVA detection based on number of columns in the first row.

**Comment by prof-joe** [comment]
nikkei<-getSymbols.yahooj("998407.t",from=as.Date("2014-04-01"),to=as.Date("2015-03-31"),
auto.assign=FALSE)

This may be closely related to this issue. However, this does not work. Nikkei is a more important index than TOPIX for JP economy. Can you consider or setup another issue ? Thank you.

**Comment by joshuaulrich** [comment]
@prof-joe, this is unrelated. The problem with your code is that the symbol code `"998407.T"` does not have any data (likely because the exchange is incorrect).  It works if you omit the exchange symbol.

```r
R> nikkei <- getSymbols.yahooj("998407", from="2014-04-01", to="2015-03-31", auto.assign=FALSE)
R> head(nikkei)
           YJ998407.Open YJ998407.High YJ998407.Low YJ998407.Close
2014-04-01      14870.51      14870.51     14751.29       14791.99
2014-04-02      14897.88      15069.61     14893.17       14946.32
2014-04-03      15009.18      15164.39     14976.36       15071.88
2014-04-04      15005.54      15098.38     15000.69       15063.77
2014-04-07      14880.82      14895.58     14764.37       14808.85
2014-04-08      14715.80      14740.10     14605.31       14606.88
```

**Comment by prof-joe** [comment]
I am preparing tomorrow's class in my university for finance with R. 
This helps me a lot.
Thank you very much!
