### ISSUE TITLE
Oanda data provided for nonsense currencies

### ISSUE THREAD

**Issue by GShotwell** [joshuaulrich/quantmod#59]
Thanks for the great package, I noticed a slightly problematic bit of behavior. When you query a nonexistent currency, for instance `getSymbols("USD/@#$", src="oanda")` it returns an object just like any other. I'm not sure it's easy to fix, but it would be nice to throw an error when you asked for a non-existent currency pair.

**Comment by joshuaulrich** [comment]
Note that this throws an error in version 0.4-8, but it's not terribly informative.  Should still add a check to see whether the currency pair is legitimate.

**Comment by joshuaulrich** [comment]
Closing because the current behavior seems good enough:

```r
Error in getSymbols.oanda(Symbols = "USD/@#$", env = <environment>, verbose = FALSE,  : 
  Unable to import "USD/@#$".
HTTP error 400.
```

Thanks for the contribution!
