### ISSUE TITLE
Passing date format to getSymbols()

### ISSUE THREAD

**Issue by aickley** [joshuaulrich/quantmod#60]
I think it is inconvenient and confusing that `getSymbols()` is insensitive to the `format` argument. The only way I could specify it is by a call to `setSymbolLookup()` e.g.
```
setSymbolLookup(ticker=list(source="csv", format=FORMAT))
```

This behaviour is in contrast to the other arguments. For instance, one can either set `src` or `dir` in `setSymbolLookup` or use them as arguments to `getSymbols()` directly.

**Comment by joshuaulrich** [comment]
I assume you're only referring to `getSymbols.csv`. Can you please verify?  If so, the fix to #48 allows you to specify `format` via `...`, so I'm not sure what behavior you want.

**Comment by aickley** [comment]
Joshua, thanks a lot for your quick reply. I checked and this is fixed in the upstream version indeed.

**Comment by joshuaulrich** [comment]
Thanks for confirming the prior fix works for you.
