### ISSUE TITLE
Option to have symbols as a column instead of column prefix.

### ISSUE THREAD

**Issue by jtkiley** [joshuaulrich/quantmod#69]
It would be really nice to have a way to include the symbols in their own column so that the data have a symbol-day shape rather than a day shape with many columns. Among its many uses, `quantmod` has deeper readily-available historical data than some academic databases.

My end use is condensing the data (to quarters or years) and then merging that data with a larger dataset that has a firm-year shape. I list some resources for doing this below, but it seems like a potentially common use for academic researchers, and, thus, you may be interested in incorporating it directly.

So, for example, the current objects look like this:

```
           AAPL.Open AAPL.High AAPL.Low AAPL.Close AAPL.Volume
1982-01-04    22.125    22.125   22.000     22.000    17813600
1982-01-05    21.125    21.125   20.875     20.875     8960000
1982-01-06    20.750    20.750   20.625     20.625    16520000
1982-01-07    19.250    19.250   19.000     19.000    17511200
1982-01-08    19.875    20.000   19.875     19.875    14151200
1982-01-11    18.750    18.750   18.625     18.625     8332800
           AAPL.Adjusted
1982-01-04      0.333894
1982-01-05      0.316820
1982-01-06      0.313026
1982-01-07      0.288363
1982-01-08      0.301643
1982-01-11      0.282672
```

And, I would prefer this: 

```
         time   Open   High    Low  Close   Volume Adjusted Symbol
1: 1982-01-04 22.125 22.125 22.000 22.000 17813600 0.333894   AAPL
2: 1982-01-05 21.125 21.125 20.875 20.875  8960000 0.316820   AAPL
3: 1982-01-06 20.750 20.750 20.625 20.625 16520000 0.313026   AAPL
4: 1982-01-07 19.250 19.250 19.000 19.000 17511200 0.288363   AAPL
5: 1982-01-08 19.875 20.000 19.875 19.875 14151200 0.301643   AAPL
6: 1982-01-11 18.750 18.750 18.625 18.625  8332800 0.282672   AAPL
```

Currently, I accomplish this using the following:
1. Create a list of symbols.
2. Loop through each one, using `getSymbols()`.
3. Feed that `xts` object to the function in this [StackOverflow Answer](http://stackoverflow.com/a/27358897) to get a `data.table` with symbols in their own column.
4. `rbind()` each symbol's data into one big `data.table`.
5. Collapse and merge data as needed.

The best enhancement in my view would be a function that can be fed a list of symbols, beginning and end dates, a list of requested columns, and whatever other parameters, and would return a `data.table` (or similar) with all of the data. Obviously it's not that big of a deal to do ourselves, but it may be a common enough use case and a modest enough development task to build in.

**Comment by joshuaulrich** [comment]
quantmod isn't the right place for something like this.  You're asking for a different data structure, and quantmod doesn't provide data structures.  It simply uses xts, and most (all?) of the functions in quantmod expect either an xts object or something that can be coerced to xts.

Your current solution could be simplified to:

```r
dataEnv <- new.env()
getSymbols(symbolList, env=dataEnv)
dt <- rbindlist(eapply(dataEnv, as.data.table.xts))
```

If anything, this seems like something that could be added to the `as.data.table.xts` method.

**Comment by joshuaulrich** [comment]
Closing, since quantmod isn't the place for new data structures.
