### ISSUE TITLE
getSymbol output=csv not working for src = "google" for Indian Market - NSE

### ISSUE THREAD

**Issue by AnandMann** [joshuaulrich/quantmod#78]
I can fetch data from google for both US and Brazilian market 

### getSymbol can't convert csv file from Indian exchanges NSE & BSE 
Error in download.file(paste(google.URL, "q=", Symbols.name, "&startdate=",  : 
  cannot open URL 'http://finance.google.com/finance/historical?q=NSE:INFY&startdate=Aug+10,+2015&enddate=Feb+03,+2016&output=csv'
In addition: Warning message:
In download.file(paste(google.URL, "q=", Symbols.name, "&startdate=",  :
  cannot open: HTTP status was '404 Not Found'

### Works nicely for NYSE and Other market scripts
http://finance.google.com/finance/historical?q=AAPL&startdate=Aug+10,+2015&enddate=Feb+03,+2016&output=csv

http://finance.google.com/finance/historical?q=BVMF:PETR4&startdate=Aug+10,+2015&enddate=Feb+03,+2016&output=csv

**Comment by joshuaulrich** [comment]
Please provide the function call that produces the error.

**Comment by AnandMann** [comment]
Sincere apologies that should have been on the top of the query. 

`getSymbol ("NSE:INFY", src = "google", from = '2015-08-10')`

I realize that for the NSE, BSE scripts , Google Finance doesn't provide the download as csv option that we rely to fetch the data in R. It only provides the historical data table in html. 

If we run 
`getSymbol ("BVMP:PETR4", src = "google", from = '2015-08-10')`
then it can produce the output. I tested the link and it broke in the end for the NSE & BSE scripts 
**&output=csv**

**Comment by potholiday** [comment]
I also have to report the same problem
`getSymbols ("NSE:ACC", src = "google", from = "2016-08-11")`

**Comment by joshuaulrich** [comment]
This isn't an issue with quantmod.  The problem is that the data provider (Google, Yahoo, etc) do not provide the data for download.

It's possible to scrape the HTML, but that is a lot of work and prone to very high maintenance costs (i.e. the code might need to be completely rewritten if the HTML changes).
