### ISSUE TITLE
adjustOHLC for string

### ISSUE THREAD

**Issue by athompson-kz1991** [joshuaulrich/quantmod#85]
Hi,

The function `adjustOHLC` seems to work for the object produced with `getSymbols`, but not for strings of that symbol, even if `get` is used. For example, this works:
```
getSymbols("SPY")
adjustOHLC(SPY)
```

But this does not:
```
getSymbols("SPY")
adjustOHLC(get("SPY"))
```

Best,

Alex

**Comment by joshuaulrich** [comment]
This is documented.  See `?adjustOHLC` and the `symbol.name` argument.

```r
adjustOHLC(get("SPY"), symbol.name="SPY")
```
