### ISSUE TITLE
getSymbol works, getFX doesn't

### ISSUE THREAD

**Issue by mgazzin** [joshuaulrich/quantmod#86]
Dear team, I want to let you know I have some issue with getFX.
Please check the following output.
The error is in downloading the following URL:

[http://www.oanda.com/currency/historical-rates/download?quote_currency=USD&end_date=2016-03-31&start_date=2016-01-01&period=daily&display=absolute&rate=0&data_range=d90&price=mid&view=table&base_currency_0=EUR&base_currency_1=&base_currency_2=&base_currency_3=&base_currency_4=&download=csv](url)

But if I use it in the browser, it works.

Do you have an idea of what is the reason that cause this?
Thanks.
Marco.

`
R version 3.2.4 Revised (2016-03-16 r70336) -- "Very Secure Dishes"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Previously saved workspace restored]

> require(quantmod)
Loading required package: quantmod
Loading required package: xts
Loading required package: zoo

Attaching package: ‘zoo’

The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric

Loading required package: TTR
Version 0.4-0 included new data defaults. See ?getSymbols.
> sessionInfo()
R version 3.2.4 Revised (2016-03-16 r70336)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.4 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=de_CH.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=de_CH.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=de_CH.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] quantmod_0.4-5 TTR_0.23-1     xts_0.9-7      zoo_1.7-12    

loaded via a namespace (and not attached):
[1] grid_3.2.4      lattice_0.20-33
> getSymbols(c('QQQ','SPY'))
    As of 0.4-0, ‘getSymbols’ uses env=parent.frame() and
 auto.assign=TRUE by default.

 This  behavior  will be  phased out in 0.5-0  when the call  will
 default to use auto.assign=FALSE. getOption("getSymbols.env") and 
 getOptions("getSymbols.auto.assign") are now checked for alternate defaults

 This message is shown once per session and may be disabled by setting 
 options("getSymbols.warning4.0"=FALSE). See ?getSymbols for more details.
[1] "QQQ" "SPY"
> getFX("USD/EUR", from='2016-01-01')
Error in download.file(oanda.URL, destfile = tmp, quiet = !verbose) : 
  cannot open URL 'http://www.oanda.com/currency/historical-rates/download?quote_currency=USD&end_date=2016-03-31&start_date=2016-01-01&period=daily&display=absolute&rate=0&data_range=d90&price=mid&view=table&base_currency_0=EUR&base_currency_1=&base_currency_2=&base_currency_3=&base_currency_4=&download=csv'
> 
`

**Comment by mgazzin** [comment]
Problem solved using the following:

options('download.file.method'='libcurl')

Thanks.

**Comment by joshuaulrich** [comment]
Duplicate of #83.
