### ISSUE TITLE
Guidance on integrating quantmod with d3

### ISSUE THREAD

**Issue by debsush** [joshuaulrich/quantmod#89]
Hi,

This is no issue or bug but a request for some guidance.  I would like to make my chartSeries more interactive by adding some d3 components like tooltip and cross hair to it.  Are you aware of anyone who has developed your package charts on those lines.  If no, can you suggest some basic ways in which this can be achieved.  I would in that case give it a try.

Reference: https://github.com/ScottLogic/d3fc

I really like your package charts and would like to build on it

Regards,
SD

**Comment by joshuaulrich** [comment]
Have you seen [dygraphs](https://rstudio.github.io/dygraphs/)? Other than that, I'm not well-informed about this space. @timelyportfolio, do you have any suggestions?

**Comment by timelyportfolio** [comment]
There is a GSOC project to potentially partially address this, but it is quite a project and unfortunately is not a simple drop-in.  I did an experiment here http://www.buildingwidgets.com/blog/2015/9/10/week-36-stockchartr.  The other two very good contenders are `d3fc` and `techan-js`.

**Comment by braverock** [comment]
I think we'll have a path to do this by the end of the summer GSoC project.  The key is to have chartSeries/chart_Series return data via invisible().  Then a wrapper is relatively easy to write for whatever dynamic charting widget one prefers.

**Comment by braverock** [comment]
incidentally, chartSeries and chart_Series will have the same underlying engine: plot.xts, by the end of the summer if everything goes (mostly) according to plan.

**Comment by debsush** [comment]
This is great news.  Cannot wait to see the release of it.  I hope the
announcement will be made here in this forum

On Thu, Jun 2, 2016 at 10:07 PM, Brian G. Peterson <notifications@github.com

**Comment by debsush** [comment]
@ timelyportfolio
I am looking for technical indicators etc. as well.  I currently use quantmod but would be nice if I could pass some of the functions in R over to the chart in JS seamlessly.  Also, it would be nice to be able to add a given JS chart component (from d3fc) into a chart/existing htmlwidget in R 

Thank you
SD

**Comment by GoChartingAdmin** [comment]
Was wondering if there is any update on the GSOC project.  Thank you

**Comment by GoChartingAdmin** [comment]
Simply following up....any updates on the GSOC project yet?

**Comment by joshuaulrich** [comment]
Closing, since this is a question and cannot be resolved with a code change.

@GoChartingAdmin The new `plot.xts()` has been in xts since version 0.10-0.
